### ISSUE TITLE
[systeminfo] Can't install systeminfo addon

### ISSUE THREAD

**Issue by sasbibic** [openhab/openhab-addons#11294]
## Expected Behavior
Entering systeminfo into addon.cfg is expected addon to install correctly.

## Current Behavior
After saving addon.cfg I get following error into openhab.log

`2021-09-23 12:23:29.296 [ERROR] [core.karaf.internal.FeatureInstaller] - Failed installing 'openhab-binding-systeminfo': Error:
	Error downloading mvn:com.github.oshi/oshi-core/5.8.2`

## Steps to Reproduce (for Bugs)
Append systeminfo to line:
`binding=...,systeminfo`

## Context
Can't use systeminfo binding.

## Your Environment
Rsapberry PI 4 fully upgraded.
openHAB 3.2.0 Build #2500

**Comment by wborn** [comment]
It's probably because the dependencies got updated in https://github.com/openhab/openhab-addons/pull/11274 and these dependencies are missing in the openHAB Artifactory Maven repository. Maybe @kaikreuzer can add them?

**Comment by kaikreuzer** [comment]
Done - issue should therefore be fixed!

**Comment by sasbibic** [comment]
Thank you for quick response and for resolving the issue. I'll check this ASAP.

Regards

Regards
/Saš

**Comment by sasbibic** [comment]
Issue resolved. In version openHAB 3.2.0 Build #2507 systeminfo add-on installs without problem.

**Comment by clinique** [comment]
This issue is back on last snapshot (build #4108)

`[ERROR] [core.karaf.internal.FeatureInstaller] - Failed installing '....long list of pending to install bindings ....': Error: Error downloading mvn:com.github.oshi/oshi-core/6.5.0`

**Comment by wborn** [comment]
The OSHI library got updated in https://github.com/openhab/openhab-addons/pull/16821.
Maybe @kaikreuzer can upload it to Artifactory?
Meanwhile you can use the KAR file as workaround.

**Comment by mhilbush** [comment]
Ping @kaikreuzer

**Comment by kaikreuzer** [comment]
Done! Sorry for the delay.
