### ISSUE TITLE
[ipcamera] communication errors still happening A LOT

### ISSUE THREAD

**Issue by jimtng** [openhab/openhab-addons#12962]
I am on the latest snapshot, and I am still seeing this a lot in my log:

```
10:44:44.343 [INFO ] [hab.event.ThingStatusInfoChangedEvent] - Thing 'ipcamera:dahua:driveway' changed from ONLINE to OFFLINE (COMMUNICATION_ERROR): Connection Timeout: Check your IP and PORT are correct and the camera can be reached.
10:44:49.364 [INFO ] [hab.event.ThingStatusInfoChangedEvent] - Thing 'ipcamera:dahua:driveway' changed from OFFLINE (COMMUNICATION_ERROR): Connection Timeout: Check your IP and PORT are correct and the camera can be reached. to ONLINE
10:44:50.364 [INFO ] [mera.internal.handler.IpCameraHandler] - The alarm stream was not running for camera 10.1.99.13, re-starting it now
```

**Comment by peterhoeg** [comment]
Are you sure that this is a consequence of the binding and not just because of dodgy cameras? I have a bunch of different cheapo Chinese cams running and some of them exhibit the same behaviour as you are seeing whereas 2 others (running the dafanghacks custom "firmware") do not.

**Comment by jimtng** [comment]
My cameras are Dahua. I noticed that if I increased the timeout in the ipcamera code from 500ms to 2s, I experienced a lot fewer offline/online errors.

**Comment by Skinah** [comment]
Are the cameras wifi or rj45? If your still getting them even at a lower rate at a 2second timeout then it would indicate something is stopping the network traffic from getting through. Perhaps you have reached the limits of a switch or router?

**Comment by Skinah** [comment]
Is this still happening? One thing worth checking if these are Dahua or Amcrest (made by Dahua) is to look to see if the cameras are creating a HTTP 500 error code when doing DEBUG or TRACE level logging. This work around is needed for some cameras and you can reproduce it in any web browser, so it is not a binding issue..

https://community.openhab.org/t/amcrest-and-dahua-work-around-for-http-500-errors/108231

**Comment by jimtng** [comment]
I don't think the HTTP Error 500 is related. Would a HTTP Error code 500 cause a Connection Timed out in the binding?

**Comment by Skinah** [comment]
I believe it will be connected to your issue, IF you are actually getting a 500 error just before the disconnect and reconnect occurs. A http 500 error means it is a serious error in the cameras http server and this causes the camera to auto reboot and hence the binding is doing the right thing by showing offline until the camera has rebooted and come back online.

1. Try the work around.
2. Use the logs to confirm that they are happening at the same time.

Since it is possible to trigger this 500 error by using any web browser and calling the snapshot URL twice spaced closely together, if this is the cause then it should be reported to Dahua as a possible bug for them to comment on.

**Comment by Skinah** [comment]
@jimtng Can you check the logs AND also try the workaround/fix to see if this is something that needs looking into in more depth or is already known and solved?

**Comment by jimtng** [comment]
If nobody else is experiencing this issue, go ahead and close it. I'll live with it or implement a different solution.

**Comment by jimtng** [comment]
For the record, I didn't see any 500 errors. Just time outs.

**Comment by Skinah** [comment]
This is not the best place to ask if anyone else has the same issue, try the forum instead in a new thread.
I would not like to close this until the cause is found and any bugs fixed. Recently I found major bugs in the binding and no one was bothering to report them, then when they were fixed I had numerous people say they had the issue and were ignoring it. Lets work toward solving it so others can enjoy a better experience as well as your issue gets fixed.

 What I need to know is how can I reproduce it, or if that is not possible, what makes it worse or better. You wrote that increasing the timeout from 500ms to 2000 helped. How often is this occuring? every hour, every five minutes, only once a week?

To be 100% clear the 500 http error will not show up in the logs unless DEBUG level in the logs is selected.
https://github.com/openhab/openhab-addons/blob/42d93c3b970bdd81496b25e2c3dadcaf27707878/bundles/org.openhab.binding.ipcamera/src/main/java/org/openhab/binding/ipcamera/internal/MyNettyAuthHandler.java#L175

Is there something your asking the camera to do when the camera goes offline? Are you streaming the camera non stop? What is the camera doing so I can setup a test doing the same exact thing that yours is doing? Is it a wifi camera? Posting some logs of when it occurs would be helpful if you used DEBUG level when it occurs. Info level is not helpful to help diagnose an issue.

**Comment by jimtng** [comment]
I haven't looked into this much lately, however the problem is still very much there.

The binding has had 22+ disconnections against each camera in the past 22 hours. 

```
$ zcat events.log.7.gz | grep ipcamera:dahua:driveway | grep "\. to ONLINE" | wc -l
22
$ zcat events.log.7.gz | grep ipcamera:dahua:frontporch | grep "\. to ONLINE" | wc -l
24
$ zcat events.log.7.gz | grep ipcamera:dahua:street | grep "\. to ONLINE" | wc -l
22
```

I'm pretty sure the disconnections weren't caused by HTTP 500. It was disconnected due to some sort of timeout.

I have tested the connection to the cameras using curl, running inside screen sessions. They haven't disconnected while the binding disconnected twice during the same period (around 12 hours).

**Comment by Skinah** [comment]
I'm sorry but I really am not able to help, unless this gets narrowed down as I cannot reproduce it. You said "I'm pretty sure" which means you have not fully ruled it out as a cause. If it is around once an hour, then it really should not be hard to place the logs into DEBUG for 2-3 hours and then do a quick search looking for the above log line I highlighted above. Also you have not outlined what your tests are doing for me to know what it rules out as a cause or still leaves open to be possible. I can not assist without more information that helps to narrow the cause. You could also change the log line to INFO level and create your own build of the binding and add some more logs in to capture any timeouts.

**Comment by jimtng** [comment]
Sorry I haven't looked into this more deeply. I'll reopen if I ever had any more info.
