### ISSUE TITLE
[Netatmo] Polling leads to missing values in some channels - Smart Video Doorbell

### ISSUE THREAD

**Issue by HaKuNaCH** [openhab/openhab-addons#13002]
Issue came-up during the webhook investigations in :
https://github.com/openhab/openhab-addons/pull/12972#issuecomment-1164042787

### Expected Behavior
Periodical polling should deliver the values from /getevents

### Current Behavior
Polling does update the following channels with NULL:
```
sub-event#snapshot
sub-event#snapshot-url
sub-event#event
sub-event#event-url
sub-event#message
```

### Possible Solution
Values must be taken from /getevents call.
Example (I left 1 event in, but all the follwowing events also contain the same attributes and all with values):
```
{
	body: {
		home: {
			id: "xxxxxxxxxxxxxxxxxxxxxxxx",
			events: [{
				id: "xxxxxxxxxxxxxxxxxxxxxxxx",
				type: "outdoor",
				time: 1655917778,
				module_id: "xx:xx:xx:xx:xx:xx",
				video_id: "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
				video_status: "available",
				subevents: [{
					id: "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
					type: "human",
					time: 1655917778,
					verified: true,
					offset: 1,
					snapshot: {
						url: "https://netatmocameraimage.blob.core.windows.net/production/xxxxxxxxxxxxxxxxxxx",
						
					},
					vignette: {
						url: "https://netatmocameraimage.blob.core.windows.net/production/xxxxxxxxxxxxxxxxxxx",
						
					},
					message: "Person erfasst"
				}]
			},

			.. around 40 entries, all with the same attributtes and values are present in all ..

			]
		}
	},
	status: "ok",
	time_exec: 0.042575836181640625,
	time_server: 1655967343
}
```
If required, I can also post examples from:
/homedata
/homestatus

According to the documentation, all other GET API's are deprecated
https://dev.netatmo.com/apidocumentation/security#documentation

### Steps to Reproduce (for Bugs)
1. Install/configure netatmo binding incl. webhook
2. add all available channels
3. add item to the channels
4. check the values after polling

**Comment by lolodomo** [comment]
@clinique : any news?

**Comment by lolodomo** [comment]
Reading again this issue, I understand that something is not correctly handled when an event contains sub-event(s). The sub-event(s) would be ignored.
Do you agree @clinique ?
The problem is that we don't have at channel level this notion of event and sub-event. Should we merge the event with its sub-event ?
What to do if an event contains several sub-events ? Should we trigger several event updates on channels level ?

**Comment by clinique** [comment]
> Reading again this issue, I understand that something is not correctly handled when an event contains sub-event(s). The sub-event(s) would be ignored. Do you agree @clinique ? The problem is that we don't have at channel level this notion of event and sub-event. Should we merge the event with its sub-event ? What to do if an event contains several sub-events ? Should we trigger several event updates on channels level ?

I adressed this one while working on the resolution of #15883, the PR is this one : https://github.com/openhab/openhab-addons/pull/16681

SubEvents are now handled. One event can have multiple subevent and each sub will be handled sequentially.

**Comment by lolodomo** [comment]
@clinique : is this issue now fixed with the last merges ?

**Comment by clinique** [comment]
From my standpoint and understanding of the issue, yes.

**Comment by lolodomo** [comment]
Thank you @clinique 
@HaKuNaCH : please reopen if your issue is still not fully resolved after all the recent changes.

**Comment by HaKuNaCH** [comment]
Unfortunately, I cannot reopen the issue, because the issue is not fixed.

The following channels get the state, but the state gets overwritten immediately with NULL.
At least on OH 4.2.0.M3.

Affected channels:
sub-event#snapshot
sub-event#snapshot-url
sub-event#vignette
sub-event#vignette-url
last-event#video-status
last-event#local-video-url
last-event#vpn-video-url

Could you please reopen the issue. If you need more logs, please contact me.
Thanks

**Comment by HaKuNaCH** [comment]
Currently, I'm using a workaround to have the lastest state of the items, by adding the state if not NULL to a temporary item via a jython rule.

`@rule("Netatmo update temorary items", description="Updates the temporary netatmo items if not NULL", tags=["netatmo"])
@when("Item DoorbellEventSnapshot changed")
@when("Item DoorbellEventSnapshotUrl changed")
@when("Item DoorbellVignette changed")
@when("Item DoorbellVignetteUrl changed")
@when("Item DoorbellLastVideoStatus changed")
@when("Item DoorbellLastVideoLocalURL changed")
@when("Item DoorbellLastVideoVpnURL changed")
def netatmoUpdateTempItems(event):
    #log.warn("Rule: Netatmo netatmoUpdateTempItems started.")

    if unicode(event.itemState) != "NULL":
        events.postUpdate(unicode(event.itemName) + u"Temp", unicode(event.itemState.toFullString()))
        #log.warn("DEBUG: ITEM=" + unicode(event.itemName) + u"Temp updated.")

    #log.warn("Rule: Netatmo netatmoUpdateTempItems ended.")
`

**Comment by lsiepel** [comment]
@clinique are you able to comment? You seem to be the expert on this binding ;-)

**Comment by clinique** [comment]
Will come back on this now.

**Comment by clinique** [comment]
Hello @HaKuNaCH . Could you please try [this patched version](https://drive.google.com/file/d/1y-Bwelx9kHn46QfujJTnb2K6m4bYsItz/view?usp=drive_link) and give me your feed-back.
This involves webhook and is difficult to reproduce for me, I'll need your help.

**Comment by HaKuNaCH** [comment]
Thanks @clinique 
I just updated to 4.3.0.M1 and installed your patched version of the Netatmo binding.
I'll observe the events in the next couple of days and will provide feedback here.

**Comment by clinique** [comment]
Thanks for your detailed analysis @HaKuNaCH , it is very helpfull. So here's a [second corrective version](https://drive.google.com/file/d/1E0KO6YZ_3ktUjWTOIqgKKbk5L3t7rIUn/view?usp=drive_link).

**Comment by HaKuNaCH** [comment]
Here are my findings.

**These are still NOK -> they are updated correctly on event, but finally got updated with NULL again**
_zcat -f events.log* | grep "'DoorbellEventSnapshot'" | sort_

```
2024-09-09 09:19:30.962 [INFO ] [openhab.event.ItemStateChangedEvent ] - Item 'DoorbellEventSnapshot' changed from NULL to raw type (image/jpeg): 177547 bytes
2024-09-09 09:26:40.807 [INFO ] [openhab.event.ItemStateChangedEvent ] - Item 'DoorbellEventSnapshot' changed from raw type (image/jpeg): 177547 bytes to NULL
```

_zcat -f events.log* | grep "'DoorbellVignette'" | sort_

```
2024-09-09 09:18:53.164 [INFO ] [openhab.event.ItemStateChangedEvent ] - Item 'DoorbellVignette' changed from NULL to raw type (image/jpeg): 16559 bytes
2024-09-09 09:26:40.820 [INFO ] [openhab.event.ItemStateChangedEvent ] - Item 'DoorbellVignette' changed from raw type (image/jpeg): 16559 bytes to NULL
```

**These are now OK -> no longer update to NULL**
_zcat -f events.log* | grep "'DoorbellEventSnapshotUrl'" | sort_

```
2024-09-09 09:18:53.141 [INFO ] [openhab.event.ItemStateChangedEvent ] - Item 'DoorbellEventSnapshotUrl' changed from https://netatmocameraimage.blob.core.windows.net/production/... to https://netatmocameraimage.blob.core.windows.net/production/...
2024-09-09 09:19:30.962 [INFO ] [openhab.event.ItemStateChangedEvent ] - Item 'DoorbellEventSnapshotUrl' changed from https://netatmocameraimage.blob.core.windows.net/... to https://netatmocameraimage.blob.core.windows.net/production/...
2024-09-09 09:20:38.032 [INFO ] [openhab.event.ItemStateChangedEvent ] - Item 'DoorbellEventSnapshotUrl' changed from https://netatmocameraimage.blob.core.windows.net/... to https://netatmocameraimage.blob.core.windows.net/production/...
```

_zcat -f events.log* | grep "'DoorbellVignetteUrl'" | sort_

```
2024-09-09 09:18:53.164 [INFO ] [openhab.event.ItemStateChangedEvent ] - Item 'DoorbellVignetteUrl' changed from https://netatmocameraimage.blob.core.windows.net/production/... to https://netatmocameraimage.blob.core.windows.net/production/...
2024-09-09 09:19:30.985 [INFO ] [openhab.event.ItemStateChangedEvent ] - Item 'DoorbellVignetteUrl' changed from https://netatmocameraimage.blob.core.windows.net/production/... to https://netatmocameraimage.blob.core.windows.net/production/...
2024-09-09 09:20:38.046 [INFO ] [openhab.event.ItemStateChangedEvent ] - Item 'DoorbellVignetteUrl' changed from https://netatmocameraimage.blob.core.windows.net/production/6... to https://netatmocameraimage.blob.core.windows.net/production/...
```

**These are still OK -> no update to NULL** 
_zcat -f events.log* | grep "'DoorbellLastVideoStatus'" | sort_

```
2024-09-09 09:20:37.972 [INFO ] [openhab.event.ItemStateChangedEvent ] - Item 'DoorbellLastVideoStatus' changed from RECORDING to AVAILABLE
```

_zcat -f events.log* | grep "'DoorbellLastVideoLocalURL'" | sort_

```
2024-09-09 09:20:37.972 [INFO ] [openhab.event.ItemStateChangedEvent ] - Item 'DoorbellLastVideoLocalURL' changed from http://10.0.1.37/.../index.m3u8 to http://10.0.1.37/.../index.m3u8
```

_zcat -f events.log* | grep "'DoorbellLastVideoVpnURL'" | sort_

```
2024-09-09 09:32:44.655 [INFO ] [openhab.event.ItemStateChangedEvent ] - Item 'DoorbellLastVideoVpnURL' changed from https://prodvpn-eu-13.netatmo.net/restricted/.../index.m3u8 to https://prodvpn-eu-13.netatmo.net/restricted/.../index.m3u8
```

**Comment by HaKuNaCH** [comment]
Indeed, then it looks like the issue is resolved with your recent adjustments.
Thx a lot for your work !

**Comment by clinique** [comment]
> Indeed, then it looks like the issue is resolved with your recent adjustments. Thx a lot for your work !

I'll update it, taking in account the expires_at info. You'll have another patch soon.

**Comment by clinique** [comment]
Here's a [new patch](https://drive.google.com/file/d/1q_7IEfvjyA2Ay4e5k92bVWtLrkC8Hu7F/view?usp=drive_link)

**Comment by HaKuNaCH** [comment]
Tested.
Now also "EventSnapshot" and "Vignette" keep the last state.
