### ISSUE TITLE
[tapocontrol] Problem commanding Tapo P300 Power Strip channels because of min_gap

### ISSUE THREAD

**Issue by nelsonaponte** [openhab/openhab-addons#15717]
## Expected Behavior
Sending commands to the Tapo P300 channels in short intervals (from rules or UI elements) should not fail.

## Current Behavior

I recently updated to OH 4.0.1 and then to 4.0.3 but I keep having an issue sending commands to 2 of the channels (output2 and output3) of a P300 power strip with the OR Switch group I created to control the 3 items linked to the 3 channels.

Only the Things are managed with the UI, the rest is file-based configuration.

These are my items:

```
Group:Switch:OR(ON, OFF)  group_LR_PowerStrip_1_Switch "LR Power Strip 1 Switch" <switch> (group_LivingRoom)
Switch LR_PowerStrip_1_Socket1_Switch   "LR Power Strip 1 Socket 1 Switch" <switch>     (group_Plugs, group_LR_PowerStrip_1_Switch, group_LR_PowerStrip_1_Socket1)  ["Switch", "Energy", "PowerOutlet"]         { channel="tapocontrol:P300:xxxxx:ps1:actuator#output1" }
Switch LR_PowerStrip_1_Socket2_Switch   "LR Power Strip 1 Socket 2 Switch" <switch>     (group_Plugs, group_LR_PowerStrip_1_Switch, group_LR_PowerStrip_1_Socket2)  ["Switch", "Energy", "PowerOutlet"]         { channel="tapocontrol:P300:xxxxx:ps1:actuator#output2" }
Switch LR_PowerStrip_1_Socket3_Switch   "LR Power Strip 1 Socket 3 Switch" <switch>     (group_Plugs, group_LR_PowerStrip_1_Switch, group_LR_PowerStrip_1_Socket3)  ["Switch", "Energy", "PowerOutlet"]         { channel="tapocontrol:P300:xxxxx:ps1:actuator#output3" }

```

Whenever I switch any of the 3 items ON individually, the group switch gets switched ON. When I switch them OFF individually, the group switch is automatically switched OFF.
However, when I try to control the 3 items from the group switch, i.e., by switching the group switch ON or OFF, only Switch LR_PowerStrip_1_Socket1_Switch is altered, the other ones remain in their current status.

For example, Switch LR_PowerStrip_1_**Socket1**__Switch and Switch LR_PowerStrip_1_**Socket3**__Switch are ON, and thus group_LR_PowerStrip_1_Switch is also ON. If I then try to switch the group OFF (using a button on the UI or sending a command through a rule), only Switch LR_PowerStrip_1_**Socket1**__Switch is switched OFF but the other item remains ON, thus, the group also remains ON.

Likewise, if all items and the group are OFF and I try to switch the group ON, only the Socket 1 is switched ON and the other ones remain OFF.

After setting the Tapo binding to DEBUG mode I saw the following error message:

```
10:42:28.676 [DEBUG] [trol.internal.api.TapoDeviceConnector] - (tapocontrol:P300:xxxxx:ps1) command not sent because of min_gap: 1696322548676 <- 1696322548670
10:42:28.681 [DEBUG] [trol.internal.api.TapoDeviceConnector] - (tapocontrol:P300:xxxxx:ps1) command not sent because of min_gap: 1696322548681 <- 1696322548670
```

The refresh interval at the Thing (Power Strip) level is 30 seconds.

I have another OR Switch group controlling 2 P115 Tapo and 1 Kasa Smart Plugs and another for the switches of all the lights and they all work without problems. So the problem is not core OH (group switches), but maybe something directly related to the P300, as sending commands to 2 Tapo smart plugs doesn't end with errors.

## Context
I use 2 main OR Switch groups for the 3 channels of the Tapo P300 so I can quickly turn them ON/OFF with one button, or 1 command in the rules (e.g., when the home goes into Away mode), and another one to control all the smart plugs at the same time.

## Your Environment
* Version used: openHAB 4.0.3 (bug experienced from 4.0.0)
* Environment name and version (e.g. Chrome 76, Java 8, Node.js 12.9, ...): Raspberry Pi 4B (ARM64) / 4G RAM
* Operating System and version (desktop or mobile, Windows 10, Raspbian Buster, ...): CentOS 8 (64-bits)

https://community.openhab.org/t/problem-commanding-tapo-p300-power-strip-channels-because-of-min-gap/150082

**Comment by wildcs** [comment]
Nomrally the sending of requests to the device is limited by a gap of 1000ms
For 4.1-snapshot there will be a bigger change in communication protocol. I ordered a P300 for me now to investigate the problem and i hope i can resolve it.

**Comment by wildcs** [comment]
Fixed with pr https://github.com/openhab/openhab-addons/pull/15725
Until pr is merged you can manually install jar from my [oh-compile-addons](https://github.com/wildcs/oh3_compiled-addons/tree/tapocontrol)

Note: Sockets are switching one after another because the core handles commands one after another too.

**Comment by nelsonaponte** [comment]
Thanks a lot, @wildcs.
I've always used the stable version but as soon as I can I will try to check how to install the jar and make sure I don't have future problems when updating OH.
Best regards

**Comment by nelsonaponte** [comment]
Hi, @wildcs 

I finally had a chance to install the jar (https://github.com/wildcs/oh3_compiled-addons/blob/tapocontrol/org.openhab.binding.tapocontrol-4.0.4-SNAPSHOT.jar) on my OH 4.0.4 and still have the same  problem with the min_gap after trying to send a command to all the switch actuators using an OR switch. Here is the TRACE stack:

`11/19/2023 20:36:06.786 [DEBUG] [trol.internal.api.TapoDeviceConnector] - (tapocontrol:P300:98533:ps1) command not sent because of min_gap: 1700422566786 <- 1700422566780
11/19/2023 20:36:06.793 [DEBUG] [trol.internal.api.TapoDeviceConnector] - (tapocontrol:P300:98533:ps1) command not sent because of min_gap: 1700422566793 <- 1700422566780
11/19/2023 20:36:06.879 [DEBUG] [ontrol.internal.api.TapoDeviceHttpApi] - (tapocontrol:P300:98533:ps1) sendAsyncRequest failed'HttpConnectionOverHTTP@22c2faea::SocketChannelEndPoint@285ecc34{l=/XX.XX.XX.XX:39182,r=/XX.XX.XX.XX:80,ISHUT,fill=-,flush=-,to=89/0}{io=0/0,kio=0,kro=1}->HttpConnectionOverHTTP@22c2faea(l:/XX.XX.XX.XX:39182 <-> r:/XX.XX.XX.XX:80,closed=false)=>HttpChannelOverHTTP@736a7378(exchange=HttpExchange@62aaaecf{req=HttpRequest[POST /app HTTP/1.1]@578a1dda[TERMINATED/null] res=HttpResponse[null 0 null]@9eb4473[PENDING/null]})[send=HttpSenderOverHTTP@293a0785(req=QUEUED,snd=COMPLETED,failure=null)[HttpGenerator@1ed108bb{s=START}],recv=HttpReceiverOverHTTP@19b2a276(rsp=IDLE,failure=null)[HttpParser{s=CLOSED,0 of -1}]]'
11/19/2023 20:36:06.891 [DEBUG] [ontrol.internal.api.TapoDeviceHttpApi] - (tapocontrol:P300:98533:ps1) sendAsyncRequest failed'HttpConnectionOverHTTP@5e0ad184::SocketChannelEndPoint@4a265a8{l=/XX.XX.XX.XX:39178,r=/XX.XX.XX:XX:80,ISHUT,fill=-,flush=-,to=108/0}{io=0/0,kio=0,kro=1}->HttpConnectionOverHTTP@5e0ad184(l:/XX.XX.XX.XX:39178 <-> r:/XX.XX.XX.XX:80,closed=false)=>HttpChannelOverHTTP@31a0029c(exchange=HttpExchange@17ca391f{req=HttpRequest[POST /app HTTP/1.1]@1fc45c93[TERMINATED/null] res=HttpResponse[null 0 null]@8dcf5e6[PENDING/null]})[send=HttpSenderOverHTTP@3959b283(req=QUEUED,snd=COMPLETED,failure=null)[HttpGenerator@7f9d6676{s=START}],recv=HttpReceiverOverHTTP@42808dd2(rsp=IDLE,failure=null)[HttpParser{s=CLOSED,0 of -1}]]'

`

`271 │ Active │  80 │ 4.0.4                  │ org.openhab.binding.tapocontrol`

**Comment by wildcs** [comment]
Hi,
just copy the jar in de addons folder and change ownership
Look at https://community.openhab.org/t/oh3-manually-add-binding-jar/130396
So that you cant see it in the section seems to be normal. If you set log-level to trace and you copy the jar into the folde you should see in the log files the binding is initialising.

**Comment by nelsonaponte** [comment]
Changing the ownership didn't work. As you can see from the screenshot, there is another binding that I manually installed and works fine. Moreover, the linked things don't get initialized and show the following error:
![image](https://github.com/openhab/openhab-addons/assets/101673770/9b15bd3a-58a3-4353-bb81-fa1c11e206f4)

**Comment by nelsonaponte** [comment]
Hi, @wildcs 

I could finally install the snapshot binding and test this fixed. It worked!
Now, sending ON/OFF commands to the OR switch doesn't return errors and the actuators are correctly updated.

Thanks for your support!

**Comment by lsiepel** [comment]
As the corrosponding PR has not yet been merged, i re-open this. It will automatically be closed when the PR is merged.
