### ISSUE TITLE
[SolarEdge] Private API not working

### ISSUE THREAD

**Issue by m0qui** [openhab/openhab-addons#15867]
Regarding `org.openhab.binding.solaredge`: Public API works as expected using the API key. Configuring the private API results in a `CONFIGURATION_ERROR` stating _You will have to use a token and not an api key when using private API._, even thou I used a fresh token grabbed via Firefox storage inspector, not an API key.

```
solaredge:generic:test1 [ tokenOrApiKey="L***S", solarId="3***1", meterInstalled=true, usePrivateApi=false ] // working

solaredge:generic:test2 [ tokenOrApiKey="d***M", solarId="3***1", meterInstalled=true, usePrivateApi=true ] // not working
```

cc: @alexf2015

**Comment by riegelbrau** [comment]
Same here with OH 4.0.3 on openhabian 6.1.21-v8+.

**Comment by lsiepel** [comment]
@m0qui  When the token is set, it is tested to have `< 80` characters. If this test fails you get the error you mentioned. So can you double check the token length and or if it is no mistake?

@riegelbrau  You seem to have a different issue. Could you 1. also check the token length? and 2. elaborate on the issue you have with the cloud, preferrable in a seperate issue?

**Comment by m0qui** [comment]
@lsiepel Thank you for looking into this. My token is exactly 79 characters in length.

**Comment by lsiepel** [comment]
> @lsiepel Thank you for looking into this. My token is exactly 79 characters in length.
> 
> @riegelbrau Public API working fine for me for month.

Hmm sure you did not accidentally add whitespaces. I could add a trim to prevent that. But first need to make sure why you get this error as with a 79 char token this is unexpected

**Comment by m0qui** [comment]
@lsiepel yes, I just reconfigured again from scratch using a `.things` file and via the web ui. No addition white spaces.
```
solaredge:generic:wrt [ tokenOrApiKey="d*****************************************************************************A", solarId="3*****1", meterInstalled=true, usePrivateApi=true ]
```
(Used Ins to override my data, string is same length as in my actual `.things` file)

**Comment by m0qui** [comment]
Yes, I'm on 4.2.1. I also tried adding and removing a single char, to check if I can trigger a different error.
With the `SPRING_SECURITY_REMEMBER_ME_COOKIE` token I also get _Unknown_ => _Waiting for web api login_ at first, but after about 10 to 15 seconds it changes to `OFFLINE`=>`CONFIGURATION_ERROR`=>_You will have to use a token and not an api key when using private API_.

Happy to provide more logs, just tell me what you need.

**Comment by lsiepel** [comment]
Sorry, now that i re-read this topic again, i wrote down my conclusion the wrong way around:

This is right:
> When the token is set, it is tested to have < 80 characters. If that is the case you get the error you mentioned. So can you double check the token length and or if it is no mistake?
https://github.com/openhab/openhab-addons/blob/ed93eb572c072898faa21def64461ea7b5120481/bundles/org.openhab.binding.solaredge/src/main/java/org/openhab/binding/solaredge/internal/connector/WebInterface.java#L169-L170

So why is your token 79 chars and not the expected 80 (or more) ? Could you re-generate it or look up to double check there is no copy/paste error?

**Comment by patbuser** [comment]
Old topic I know, reactivating it. Private API throws a Connection Error since this morning. Error message is "gone" (as in, that's the message I get after connection attempt).

Created a new Spring Security Token and restarted OH. Didn't help. Not sure if the issue is actually on SE side.

The Public Token probably would work but it says Exceeded the 300 limit.

Using OH 4.3.4 in Docker.

**Comment by gkunz** [comment]
Can confirm. Save observation here on OH 5.2.0

**Comment by rogrun** [comment]
I am working on a solution. You can find a test version here:
https://github.com/rogrun/openhab-addons/releases/tag/Release-Solaredge-Binding-5.3.0.202607221919

I have also published a post about this in the community:
https://community.openhab.org/t/solaredge-private-api-not-working-anymore/169848/16

**Comment by gkunz** [comment]
Hi @rogrun. Good to know you are also working on a fix.

It seems that SolarEdge not just changed the API endpoint, but the new endpoint also returns a new data structure. I have therefore prototyped dedicated new data handling for the new private API [1] (it's a PoC).

Quite a few things are still missing, such as the "meterless" setup (my setup uses a meter), proper support for a battery (I have none), and new aggregate data handling.

This API change may also have an impact on the OH channels as the new API does not map 1:1 to the existing channels.

So, some issues to discuss and sort out still. Happy to discuss and test.

[1] https://github.com/gkunz/openhab-addons/commit/4704630fabcd2b8e0595979e6edfd9dfbc2c5991

**Comment by rogrun** [comment]
@gkunz I’ve taken a look at your PoC. Good work so far. You’re already much further along with it than I am with my own work. I suggest we continue the bug fixing based on your work. I’d be happy to help you with that. I have a battery and can certainly lend a hand.

**Comment by gkunz** [comment]
Thanks for the feedback @rogrun. Please note that I am digging into Openhab binding development for the first time, so any sort of feedback and joint development is welcome. In particular, I am lacking API responses for setups with a battery and without an installed meter. So, examples provided by others are appreciated.
