### ISSUE TITLE
[shelly] Some channels on Shelly Pro 3EM report NULL

### ISSUE THREAD

**Issue by hoinmic** [openhab/openhab-addons#16772]
The Shelly Pro 3EM device does not display all values, some channels display " NULL ". The debug functionality of the shelly addon shows the arrival of the corresponding data, but the channel are not updated.

Tested with the commits on the openhab-addons branch **4.2.0~M2-1** 

I have not yet discovered any errors in the shelly folder of the openhab-addons repository.

Does anyone have an idea what is wrong here?

Logs:
```sh
2024-05-18 22:29:00.050 [INFO ] [org.openhab.core.model.script.power ] - -----------------------
2024-05-18 22:29:00.050 [INFO ] [org.openhab.core.model.script.power ] - Current_Power_Meter1_Inverter: 0
2024-05-18 22:29:00.050 [INFO ] [org.openhab.core.model.script.power ] - Total_Energy_Meter1_Inverter: NULL
2024-05-18 22:29:00.050 [INFO ] [org.openhab.core.model.script.power ] - Total_Energy_Returned_Meter1_Inverter: 0
2024-05-18 22:29:00.057 [INFO ] [org.openhab.core.model.script.power ] - Reactive_Power_Meter1_Inverter: NULL
2024-05-18 22:29:00.058 [INFO ] [org.openhab.core.model.script.power ] - Voltage_Meter1_Inverter: 0
2024-05-18 22:29:00.058 [INFO ] [org.openhab.core.model.script.power ] - Current_Meter1_Inverter: 0.028
2024-05-18 22:29:00.058 [INFO ] [org.openhab.core.model.script.power ] - Power_Factor_Meter1_Inverter: 0
2024-05-18 22:29:00.058 [INFO ] [org.openhab.core.model.script.power ] - Last_Update_Meter1_Inverter: 2024-05-18T22:28:17.000+0200
2024-05-18 22:29:00.059 [INFO ] [org.openhab.core.model.script.power ] - Reset_Total_Meter1_Inverter: NULL
2024-05-18 22:29:00.059 [INFO ] [org.openhab.core.model.script.power ] - -----------------------
2024-05-18 22:29:00.059 [INFO ] [org.openhab.core.model.script.power ] - Current_Power_Meter2_Inverter: 0
2024-05-18 22:29:00.059 [INFO ] [org.openhab.core.model.script.power ] - Total_Energy_Meter2_Inverter: NULL
2024-05-18 22:29:00.059 [INFO ] [org.openhab.core.model.script.power ] - Total_Energy_Returned_Meter2_Inverter: 0
2024-05-18 22:29:00.060 [INFO ] [org.openhab.core.model.script.power ] - Reactive_Power_Meter2_Inverter: NULL
2024-05-18 22:29:00.060 [INFO ] [org.openhab.core.model.script.power ] - Voltage_Meter2_Inverter: 0
2024-05-18 22:29:00.060 [INFO ] [org.openhab.core.model.script.power ] - Current_Meter2_Inverter: 0.028
2024-05-18 22:29:00.060 [INFO ] [org.openhab.core.model.script.power ] - Power_Factor_Meter2_Inverter: 0
2024-05-18 22:29:00.060 [INFO ] [org.openhab.core.model.script.power ] - Last_Update_Meter2_Inverter: 2024-05-18T22:28:50.000+0200
2024-05-18 22:29:00.060 [INFO ] [org.openhab.core.model.script.power ] - Reset_Total_Meter2_Inverter: NULL
2024-05-18 22:29:00.061 [INFO ] [org.openhab.core.model.script.power ] - -----------------------
2024-05-18 22:29:00.061 [INFO ] [org.openhab.core.model.script.power ] - Current_Power_Meter3_Inverter: 0
2024-05-18 22:29:00.061 [INFO ] [org.openhab.core.model.script.power ] - Total_Energy_Meter3_Inverter: NULL
2024-05-18 22:29:00.061 [INFO ] [org.openhab.core.model.script.power ] - Total_Energy_Returned_Meter3_Inverter: 0.007
2024-05-18 22:29:00.061 [INFO ] [org.openhab.core.model.script.power ] - Reactive_Power_Meter3_Inverter: NULL
2024-05-18 22:29:00.061 [INFO ] [org.openhab.core.model.script.power ] - Voltage_Meter3_Inverter: 238.8
2024-05-18 22:29:00.062 [INFO ] [org.openhab.core.model.script.power ] - Current_Meter3_Inverter: 0.028
2024-05-18 22:29:00.062 [INFO ] [org.openhab.core.model.script.power ] - Power_Factor_Meter3_Inverter: 0
2024-05-18 22:29:00.062 [INFO ] [org.openhab.core.model.script.power ] - Last_Update_Meter3_Inverter: 2024-05-18T22:28:50.000+0200
2024-05-18 22:29:00.062 [INFO ] [org.openhab.core.model.script.power ] - Reset_Total_Meter3_Inverter: NULL
2024-05-18 22:29:00.062 [INFO ] [org.openhab.core.model.script.power ] - -----------------------
.....
```

Shelly-addon logs:
```sh
2024-05-18 22:29:04.073 [DEBUG] [g.shelly.internal.api2.Shelly2ApiRpc] - shellypro3em-pvinverter: NotifyStatus update received: {"src":"shellypro3em-34987a467758","dst":"shellypro3em-pvinverter","method":"NotifyStatus","params":{"ts":1.71606413072E9,"em:0":{"id":0,"a_current":0.028,"a_voltage":0.0,"a_act_power":0.0,"a_aprt_power":0.0,"a_pf":0.0,"b_current":0.027,"b_voltage":0.0,"b_act_power":0.0,"b_aprt_power":0.0,"b_pf":0.0,"c_current":0.027,"c_voltage":239.0,"c_act_power":0.0,"c_aprt_power":6.6,"c_pf":0.0,"total_current":0.082,"total_act_power":0.0,"total_aprt_power":6.561}}}
.....
```

Items file:
```sh
// Energy Meter1 Inverter
Number Current_Power_Meter1_Inverter {channel="shelly:shellypro3em:pvInverter:meter1#currentWatts"}
Number Total_Energy_Meter1_Inverter {channel="shelly:shellypro3em:pvInverter:meter1#totalKWH"}
Number Total_Energy_Returned_Meter1_Inverter {channel="shelly:shellypro3em:pvInverter:meter1#returnedKWH"}
Number Reactive_Power_Meter1_Inverter {channel="shelly:shellypro3em:pvInverter:meter1#reactiveWatts"}
Number Voltage_Meter1_Inverter {channel="shelly:shellypro3em:pvInverter:meter1#voltage"}
Number Current_Meter1_Inverter {channel="shelly:shellypro3em:pvInverter:meter1#current"}
Number Power_Factor_Meter1_Inverter {channel="shelly:shellypro3em:pvInverter:meter1#powerFactor"}
DateTime Last_Update_Meter1_Inverter {channel="shelly:shellypro3em:pvInverter:meter1#lastUpdate"}
Switch Reset_Total_Meter1_Inverter {channel="shelly:shellypro3em:pvInverter:meter1#resetTotals"}
.....
```
Rules file:
```sh
  logInfo(logName, "-----------------------")
  logInfo(logName, "Current_Power_Meter1_Inverter: " + Current_Power_Meter1_Inverter.state)
  logInfo(logName, "Total_Energy_Meter1_Inverter: " + Total_Energy_Meter1_Inverter.state)
  logInfo(logName, "Total_Energy_Returned_Meter1_Inverter: " + Total_Energy_Returned_Meter1_Inverter.state)
  logInfo(logName, "Reactive_Power_Meter1_Inverter: " + Reactive_Power_Meter1_Inverter.state)
  logInfo(logName, "Voltage_Meter1_Inverter: " + Voltage_Meter1_Inverter.state)
  logInfo(logName, "Current_Meter1_Inverter: " + Current_Meter1_Inverter.state)
  logInfo(logName, "Power_Factor_Meter1_Inverter: " + Power_Factor_Meter1_Inverter.state)
  logInfo(logName, "Last_Update_Meter1_Inverter: " + Last_Update_Meter1_Inverter.state)
  logInfo(logName, "Reset_Total_Meter1_Inverter: " + Reset_Total_Meter1_Inverter.state)
.....
```

---------------------------
Addendum:
It is noticeable that even with the UI (openhab+openhab-addons version 4.2.0~M2-1) for the Thing, only the channels

shelly:shellypro3em:pvInverter:meter1#currentWatts
shelly:shellypro3em:pvInverter:meter1#returnedKWH
shelly:shellypro3em:pvInverter:meter1#voltage
shelly:shellypro3em:pvInverter:meter1#current
shelly:shellypro3em:pvInverter:meter1#powerFactor

are suggested (for all three electricity meters). From the channels

channel="shelly:shellypro3em:pvInverter:meter1#totalKWH"
shelly:shellypro3em:pvInverter:meter1#reactiveWatts"

every trace is missing.

---------------------------
Addendum:
I have now compiled the latest version of shelly openhab-addon from mainbranch . It seems that the BaseHandler receives all data.

But still no output on the channels.

```sh
2024-05-19 13:41:22.163 [DEBUG] [y.internal.handler.ShellyBaseHandler] - shellypro3em-pvinverter: Channel device#deviceName updated with Pro3EM_PV (type class org.openhab.core.library.types.StringType).
2024-05-19 13:41:22.164 [DEBUG] [y.internal.handler.ShellyBaseHandler] - shellypro3em-pvinverter: Channel device#uptime updated with 1344 s (type class org.openhab.core.library.types.QuantityType).
2024-05-19 13:41:22.164 [DEBUG] [y.internal.handler.ShellyBaseHandler] - shellypro3em-pvinverter: Channel device#uptime updated with 1344 s (type class org.openhab.core.library.types.QuantityType).
2024-05-19 13:41:22.164 [DEBUG] [y.internal.handler.ShellyBaseHandler] - shellypro3em-pvinverter: Channel meter1#currentWatts updated with 0 W (type class org.openhab.core.library.types.QuantityType).
2024-05-19 13:41:22.164 [DEBUG] [y.internal.handler.ShellyBaseHandler] - shellypro3em-pvinverter: Channel meter1#totalKWH updated with 0 kWh (type class org.openhab.core.library.types.QuantityType).
2024-05-19 13:41:22.164 [DEBUG] [y.internal.handler.ShellyBaseHandler] - shellypro3em-pvinverter: Channel meter1#returnedKWH updated with 0 kWh (type class org.openhab.core.library.types.QuantityType).
2024-05-19 13:41:22.164 [DEBUG] [y.internal.handler.ShellyBaseHandler] - shellypro3em-pvinverter: Channel meter1#reactiveWatts updated with 0 W (type class org.openhab.core.library.types.QuantityType).
2024-05-19 13:41:22.164 [DEBUG] [y.internal.handler.ShellyBaseHandler] - shellypro3em-pvinverter: Channel meter1#voltage updated with 0 V (type class org.openhab.core.library.types.QuantityType).
2024-05-19 13:41:22.165 [DEBUG] [y.internal.handler.ShellyBaseHandler] - shellypro3em-pvinverter: Channel meter1#current updated with 0.027 A (type class org.openhab.core.library.types.QuantityType).
2024-05-19 13:41:22.165 [DEBUG] [y.internal.handler.ShellyBaseHandler] - shellypro3em-pvinverter: Channel meter1#powerFactor updated with 0 % (type class org.openhab.core.library.types.QuantityType).
2024-05-19 13:41:22.165 [DEBUG] [y.internal.handler.ShellyBaseHandler] - shellypro3em-pvinverter: Channel meter1#lastUpdate updated with 2024-05-19T13:41:22.000+0200 (type class org.openhab.core.library.types.DateTimeType).
.....
```

**Comment by hoinmic** [comment]
I have now compiled the latest version of shelly openhab-addon from mainbranch . It seems that the BaseHandler receives all data.

But still no output on the channels.

```sh
2024-05-19 13:41:22.163 [DEBUG] [y.internal.handler.ShellyBaseHandler] - shellypro3em-pvinverter: Channel device#deviceName updated with Pro3EM_PV (type class org.openhab.core.library.types.StringType).
2024-05-19 13:41:22.164 [DEBUG] [y.internal.handler.ShellyBaseHandler] - shellypro3em-pvinverter: Channel device#uptime updated with 1344 s (type class org.openhab.core.library.types.QuantityType).
2024-05-19 13:41:22.164 [DEBUG] [y.internal.handler.ShellyBaseHandler] - shellypro3em-pvinverter: Channel device#uptime updated with 1344 s (type class org.openhab.core.library.types.QuantityType).
2024-05-19 13:41:22.164 [DEBUG] [y.internal.handler.ShellyBaseHandler] - shellypro3em-pvinverter: Channel meter1#currentWatts updated with 0 W (type class org.openhab.core.library.types.QuantityType).
2024-05-19 13:41:22.164 [DEBUG] [y.internal.handler.ShellyBaseHandler] - shellypro3em-pvinverter: Channel meter1#totalKWH updated with 0 kWh (type class org.openhab.core.library.types.QuantityType).
2024-05-19 13:41:22.164 [DEBUG] [y.internal.handler.ShellyBaseHandler] - shellypro3em-pvinverter: Channel meter1#returnedKWH updated with 0 kWh (type class org.openhab.core.library.types.QuantityType).
2024-05-19 13:41:22.164 [DEBUG] [y.internal.handler.ShellyBaseHandler] - shellypro3em-pvinverter: Channel meter1#reactiveWatts updated with 0 W (type class org.openhab.core.library.types.QuantityType).
2024-05-19 13:41:22.164 [DEBUG] [y.internal.handler.ShellyBaseHandler] - shellypro3em-pvinverter: Channel meter1#voltage updated with 0 V (type class org.openhab.core.library.types.QuantityType).
2024-05-19 13:41:22.165 [DEBUG] [y.internal.handler.ShellyBaseHandler] - shellypro3em-pvinverter: Channel meter1#current updated with 0.027 A (type class org.openhab.core.library.types.QuantityType).
2024-05-19 13:41:22.165 [DEBUG] [y.internal.handler.ShellyBaseHandler] - shellypro3em-pvinverter: Channel meter1#powerFactor updated with 0 % (type class org.openhab.core.library.types.QuantityType).
2024-05-19 13:41:22.165 [DEBUG] [y.internal.handler.ShellyBaseHandler] - shellypro3em-pvinverter: Channel meter1#lastUpdate updated with 2024-05-19T13:41:22.000+0200 (type class org.openhab.core.library.types.DateTimeType).
.....
```

**Comment by lsiepel** [comment]
Something you can look into @markus7017 ?

**Comment by hoinmic** [comment]
Hi Markus

I have implemented your solution. Unfortunately without success, the behaviour is still the same. The two channels "totalKWH" and "reactiveWatts" are missing.

I have done the following:

```sh
wget -O org.openhab.binding.shelly-4.2.0-SNAPSHOT.jar https://github.com/markus7017/myfiles/blob/master/shelly/org.openhab.binding.shelly-4.2.0-SNAPSHOT.jar?raw=true  

# -> removed all shelly things

# -> Uninstall Shelly binding form UI
openhab-cli console   -> feature:install openhab-transport-coap

systemctl stop openhab.service
sudo cp org.openhab.binding.shelly-4.2.0-SNAPSHOT.jar  /usr/share/openhab/addons
systemctl start openhab.service

openhab-cli console   -> bundle:list

added shelly pro 3em thing
```
```sh
....
290 │ Resolved │  80 │ 2.7.4                 │ Californium (Cf) Core
291 │ Resolved │  80 │ 2.7.4                 │ Californium (Cf) Element Connector
292 │ Resolved │  80 │ 2.7.4                 │ Californium (Cf) OSGi
293 │ Resolved │  80 │ 2.7.4                 │ Scandium (Sc) Core
294 │ Resolved │  80 │ 4.2.0.202405241838    │ openHAB Add-ons :: Bundles :: Shelly Binding
```
![Screenshot from 2024-05-26 11-57-45](https://github.com/openhab/openhab-addons/assets/52933406/aa1b6ce9-51d3-4069-be19-cb6cbf4520eb)

**Comment by markus7017** [comment]
did you checked advanced channels?

**Comment by pgruetter** [comment]
> did you checked advanced channels?

Yes, the channels don't exist, also not in the advanced channels.

**Comment by markus7017** [comment]
I think should be solved. Please try current DEV build

**Comment by eidelsburger** [comment]
@markus7017: I have tested with https://github.com/markus7017/myfiles/blob/master/shelly/org.openhab.binding.shelly-4.3.0-SNAPSHOT.jar - ist this the right "DEV build"? With this version I have the same problem as @hoinmic describes in this thread.

**Comment by JonathanvdGHU** [comment]
I have the same problem and also tried the DEV build.

**Comment by JonathanvdGHU** [comment]
> > I have the same problem and also tried the DEV build.
> 
> Please share your results.

I am using the Shelly Pro 3EM.
![image](https://github.com/user-attachments/assets/6018e978-e571-4318-9c80-1c9ae97cca36)

This are the channels I have:
![image](https://github.com/user-attachments/assets/1906d074-6d1c-4cc1-91e4-8e4eac48b2ca)
![image](https://github.com/user-attachments/assets/2ece74c8-58df-4c24-ad8d-73cacd154a0f)

This is the channel I am missing per meter. 
![image-2024-10-10-10-04-13-833](https://github.com/user-attachments/assets/ddef4a96-3f61-4e1b-8095-425548096b06)
I manually added the channel using JSON but it doesn't do/measure anything. 

The data is collected:
![image](https://github.com/user-attachments/assets/1c58022c-d08e-48a4-99ac-e18eac975996)
![image](https://github.com/user-attachments/assets/90baa5e6-15b7-40f8-9128-04edf155a7a0)

And this is proof that I am on the DEV build: (I tried both versions, one with and without blu)
![image](https://github.com/user-attachments/assets/47662b1a-5e55-45df-8bee-604f6d91ece4)
![image](https://github.com/user-attachments/assets/bfbcfc3a-9744-4e92-a786-2832791a2780)

**Comment by JonathanvdGHU** [comment]
> > I have the same problem and also tried the DEV build.
> 
> Please share your results.

You forgot btw to reply on an other [bug](https://github.com/openhab/openhab-addons/issues/14671) I replied on😅. Not meant in a mean way.

**Comment by markus7017** [comment]
I'm working on a PR fixing various issues related to power meters

**Comment by markus7017** [comment]
@hoinmic @eidelsburger  @JonathanvdGHU 

Try this build https://github.com/markus7017/myfiles/blob/master/shelly/org.openhab.binding.shelly-5.2.0-SNAPSHOT-fixmeters.jar
and report here: https://community.openhab.org/t/shelly-binding/56862/5424

**Comment by markus7017** [comment]
Addressed in PR #20805.

**Comment by markus7017** [comment]
Addressed by PR #20805
