### ISSUE TITLE
[http] Regression in 4.2, removal of escapedUrl parameter

### ISSUE THREAD

**Issue by jamesmelville** [openhab/openhab-addons#17039]
The PR #12350 was added in 3.3 to support HTTP requests from the binding which needed URL encoded characters such as `=` and `&` to be included in requests. This worked without issue up until 4.1 but since upgrading to 4.2 my requests are now failing as they are doubly encoded. The functionality was removed in #16282. I can't see anything to suggest it was done deliberately @J-N-K ?

## Expected Behavior
Functionality described in https://github.com/openhab/openhab-addons/pull/12350#issue-1147359701

## Current Behavior
Callouts failing as the request URL which worked is now wrongly encoded.

## Possible Solution
Re-introduce functionality from #12350 

## Steps to Reproduce (for Bugs)
See #12350 

## Context
See #12350 

## Your Environment
openHAB 4.2.0 Docker Image

**Comment by J-N-K** [comment]
Hard to say if that should never have been merged. The way it was implemented breaks the possibility of using date and time in the request.

**Comment by jamesmelville** [comment]
Thanks for the response and the speedy PR @J-N-K. I can appreciate it's debatable whether that should have been merged. Looking at it with fresh eyes, I wonder if some capability to supply query parameters as an array of name value pairs would have been a better solution, although it might be a breaking change and I'm not certain it would fully deal with some of the strange ways APIs can be constructed.
I don't believe there were any issues reported with the merging of dates / commands with the change here, although I only ever used it for retrieving data from external sources, @tmaex might be able to comment.
Unless I've missed something I can't see how #17042 would enable users to make a call to an API with a URI like the example in my PR `https://example.com/api/query?q=deleted%3Dfalse%26creatorId%3Djames&sort=updatedTime+desc&count=1`, the problem is the `Util.uriFromString` logic double encoding the `%` in `%3D` to `%2536, but not encoding it if reverted to an `=` because that is a valid character in a URI.

**Comment by J-N-K** [comment]
Do you think it is safe to assume that `%[A-Fa-f0-9]{2}` (e.g. `%3D`) is always a pre-encoded value and thus `%253D` is always double-encoded? In that case we could easily revert the double-encoding. Or we could re-introduce `escapedUrl`, now that replacing command/time has been fixed and can be used with pre-encoded URLs.

**Comment by jamesmelville** [comment]
Probably irrelevant, but I still don't see where you think there was a date/time/command merge issue. The call to `String.format` happened before the encoding. I'm not set up to pull together an environment with that code in, but this (e.g.) seems to produce my expected output. Note how the user has to double the percent encoding `%%`, covered in the readme for `escapedURL`, which is how the encoded strings get past the `String.format` call and into the `URI` generation:
```
    String commandUrl = "https://example.com/api/query?q=deleted%%3Dfalse%%26creatorId%%3Djames&sort=updatedTime+desc&count=%1$tY-%1$2tm-%1$td&command=%2$s";
    String command = "ON";
      String url = String.format(commandUrl, new Date(), command);
      System.out.println(new URI(url).toString()); // https://example.com/api/query?q=deleted%3Dfalse%26creatorId%3Djames&sort=updatedTime+desc&count=2024-07-16&command=ON
      System.out.println(Util.uriFromString(url).toString()); // vs. https://example.com/api/query?q=deleted%253Dfalse%2526creatorId%253Djames&sort=updatedTime%2Bdesc&count=2024-07-16&command=ON
```
But I do now see that the handling of IDN domains was likely broken by my PR.

I guess your proposal is valid, with the exception of `%` itself, where the user would then need to encode that themselves to `%25` to get it encoded to `%2525` and then the logic back it out again?
