### ISSUE TITLE
[boschshc] Long polling fails after a few hours

### ISSUE THREAD

**Issue by mike-bike** [openhab/openhab-addons#17176]
With OpenHAB Release 4.2.0 Bosch binding stops to receiving updates from devices after a few hours. I think we had this issue last year already.  Regular "long polling" requests stop suddenly. I have tried binding delivered as well as latest snapshot versions.

What you can see below are the graphs of 3 TwinGuards. openHAB stopped receiving updates at short after 20:00 and restarted with reload of binding at ca. 23:03:
<img width="567" alt="Bildschirmfoto 2024-07-28 um 23 30 01" src="https://github.com/user-attachments/assets/49bebdc4-8033-4fef-8dc8-4c51407237b5">

## Expected Behavior
Bosch SHC Things/Channels to continue receiving updates from bridge.

## Current Behavior

Bosch SHC things stop receiving updates. Last log entries from Bosch SHC below:
```
2024-07-28 20:01:38.220 [DEBUG] [.internal.devices.bridge.LongPolling] - Long poll response: {"result":[{"deleted":true,"@type":"Dev
iceServiceData","id":"CommunicationQuality","deviceId":"hdm:ZigBee:30fb10fffe46d732"}],"jsonrpc":"2.0"}

2024-07-28 20:01:38.221 [WARN ] [mmon.WrappedScheduledExecutorService] - Scheduled runnable ended with an exception:
java.lang.NullPointerException: Cannot invoke "com.google.gson.JsonElement.getAsString()" because the return value of "com.google.gs
on.JsonObject.get(String)" is null
        at org.openhab.binding.boschshc.internal.serialization.BoschServiceDataDeserializer.deserialize(BoschServiceDataDeserializer
.java:52) ~[?:?]
        at org.openhab.binding.boschshc.internal.serialization.BoschServiceDataDeserializer.deserialize(BoschServiceDataDeserializer
.java:1) ~[?:?]
        at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:76) ~[?:?]
        at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:40) ~[?:?]
        at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:82) ~[?:?]
        at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:61) ~[?:?]
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.readIntoField(ReflectiveTypeAdapterFactory.java:212) ~[?:?]
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$FieldReflectionAdapter.readField(ReflectiveTypeAdapterFactory.
java:433) ~[?:?]
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:393) ~[?:?]
        at com.google.gson.Gson.fromJson(Gson.java:1227) ~[?:?]
        at com.google.gson.Gson.fromJson(Gson.java:1137) ~[?:?]
        at com.google.gson.Gson.fromJson(Gson.java:1047) ~[?:?]
        at com.google.gson.Gson.fromJson(Gson.java:982) ~[?:?]
        at org.openhab.binding.boschshc.internal.devices.bridge.LongPolling.handleLongPollResponse(LongPolling.java:218) ~[?:?]
        at org.openhab.binding.boschshc.internal.devices.bridge.LongPolling.onLongPollComplete(LongPolling.java:196) ~[?:?]
        at org.openhab.binding.boschshc.internal.devices.bridge.LongPolling$1.lambda$0(LongPolling.java:169) ~[?:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
        at java.lang.Thread.run(Thread.java:840) [?:?]
2024-07-28 20:01:39.822 [TRACE] [discovery.BridgeDiscoveryParticipant] - Bridge discovery invoked with mDNS service info [ServiceInfoImpl@16360636 name: 'Bosch SHC [64-da-a0-10-83-a7]._4s+7zdhr0ixl._sub._http._tcp.local.' address: '/192.168.2.61:8443 /fe80:0:0:0:66da:a0ff:fe10:83a7:8443 /2001:4dd3:492d:0:66da:a0ff:fe10:83a7:8443 ' status: 'NO DNS state: probing 1 task: null' is persistent, has data, empty]
2024-07-28 20:01:39.823 [TRACE] [discovery.BridgeDiscoveryParticipant] - Bridge discovery invoked with mDNS service info [ServiceInfoImpl@26952140 name: 'Bosch SHC [64-da-a0-10-83-a7]._http._tcp.local.' address: '/192.168.2.61:8443 /fe80:0:0:0:66da:a0ff:fe10:83a7:8443 /2001:4dd3:492d:0:66da:a0ff:fe10:83a7:8443 ' status: 'NO DNS state: probing 1 task: null' is persistent, has data, empty]
```

## Possible Solution
n.a.

## Steps to Reproduce (for Bugs)
Not sure if it is about my configuration which was running stable for months. 

## Context
Nothing specific. openHAB was running stable for hours/days.

## Your Environment

* RPi4
* openHABian, Debian 11.10
* openHAB: 4.2.0 (Build)

**Comment by david-pace** [comment]
Thanks for the bug report! The issue was already reported in the community thread linked above. But so far we had no chance of fixing it because we did not find any traces in the logs. With the stack trace you provided we can now finally tackle this issue :+1:

The symptoms look similar to a [bug I fixed a long time ago](https://github.com/openhab/openhab-addons/issues/15912), but this bug actually has a different root cause.

**Comment by mike-bike** [comment]
@david-pace , let me know if I should look for certain conditions in the log. 

**Note:** I have loaded your current latest JAR which I am testing on my PI2 to the prod PI4 yesterday and it is still getting values... Let's see, how long it will last!

**Comment by david-pace** [comment]
Thanks to the stack trace you provided I found the issue: the JSON deserialization code assumes that all `DeviceServiceData` objects contain a `path` property. In the JSON in your log we see a `DeviceServiceData` object relating to `CommunicationQuality` that has been `deleted`, but it has no `path` property. That's why the deserialization fails.

Unfortunately there is no retry mechanism if such an unexpected error happens. I now provided a [pull request](https://github.com/openhab/openhab-addons/pull/17190) that should solve both issues.

You can download a Test JAR [here](http://davidpace.de/openhab/org.openhab.binding.boschshc-4.3.0-SNAPSHOT-longpoll.jar). Note that this fix was developed independently from the relay support, therefore the relay support is not included here.

**Comment by mike-bike** [comment]
Hi @david-pace, I am happy to test but I am unsure how to reproduce the error. The current binding is running stable since I had reported the issue and provided the log. In prod I have loaded the binding you provided with the relay functionality and not seen any issues since then.

I do see both versions in the file. Not sure if you mean this:
```
2024-07-31 02:10:59.485 [DEBUG] [.internal.devices.bridge.LongPolling] - Long poll response: {"result":[{"iconId":"icon_tfk_terrace_door","rootDeviceId":"64-da-a0-10-83-a7","@type":"device","supportedProfiles":[],"profile":"FRENCH_WINDOW","deviceServiceIds":["CommunicationQuality","ShutterContact","BatteryLevel","Bypass"],"roomId":"hz_13","manufacturer":"BOSCH","serial":"18FC2600000864B0","name":"Gartentür Küche","deviceModel":"SWD2","id":"hdm:ZigBee:18fc2600000864b0","childDeviceIds":[],"status":"AVAILABLE"}],"jsonrpc":"2.0"}
2024-07-31 02:11:00.109 [DEBUG] [.internal.devices.bridge.LongPolling] - Long poll response: {"result":[{"path":"/devices/hdm:ZigBee:18fc2600000864b0/services/BatteryLevel","@type":"DeviceServiceData","id":"BatteryLevel","deviceId":"hdm:ZigBee:18fc2600000864b0"},{"path":"/devices/hdm:ZigBee:18fc2600000864b0/services/CommunicationQuality","@type":"DeviceServiceData","id":"CommunicationQuality","state":{"@type":"communicationQualityState","quality":"UNKNOWN"},"deviceId":"hdm:ZigBee:18fc2600000864b0"},{"path":"/devices/hdm:ZigBee:18fc2600000864b0/services/Bypass","@type":"DeviceServiceData","id":"Bypass","state":{"configuration":{"infinite":false,"enabled":true,"timeout":10},"@type":"bypassState","state":"BYPASS_INACTIVE"},"deviceId":"hdm:ZigBee:18fc2600000864b0"}],"jsonrpc":"2.0"}
2024-07-31 02:16:48.373 [DEBUG] [.internal.devices.bridge.LongPolling] - Long poll response: {"result":[{"rootDeviceId":"64-da-a0-10-83-a7","@type":"device","supportedProfiles":[],"profile":"GENERIC","deviceServiceIds":["CommunicationQuality","Thermostat","BatteryLevel","ValveTappet","DisplayedTemperatureConfiguration","DisplayConfiguration","DisplayDirection","TemperatureLevel","Linking","TemperatureOffset"],"roomId":"hz_5","manufacturer":"BOSCH","serial":"18FC2600000DD0E8","parentDeviceId":"roomClimateControl_hz_5","name":"HZ Kemenate ","deviceModel":"TRV_GEN2","id":"hdm:ZigBee:18fc2600000dd0e8","childDeviceIds":[],"status":"UNDEFINED"},{"path":"/devices/hdm:ZigBee:18fc2600000dd0e8/services/ValveTappet","@type":"DeviceServiceData","id":"ValveTappet","state":{"@type":"valveTappetState","position":0,"value":"VALVE_ADAPTION_SUCCESSFUL"},"deviceId":"hdm:ZigBee:18fc2600000dd0e8"},{"path":"/devices/hdm:ZigBee:18fc2600000dd0e8/services/DisplayConfiguration","@type":"DeviceServiceData","id":"DisplayConfiguration","state":{"displayOnTimeMin":5,"displayOnTimeStepSize":5,"displayOnTimeMax":30,"@type":"displayConfigurationState","displayBrightnessMin":10,"displayBrightness":70,"displayBrightnessMax":100,"displayBrightnessStepSize":10,"displayOnTime":10},"deviceId":"hdm:ZigBee:18fc2600000dd0e8"}],"jsonrpc":"2.0"}
```

**Comment by mike-bike** [comment]
... or is it about the specific device which got deleted? That's the relay which I had removed and re-added for the testing. Since I am about to do regression test on the other JAR in my test pod, I will have a look on PROD.

**Comment by mike-bike** [comment]
Seems like deletion of a Bosch device could confuse the binding. I was able to reproduce that issue while testing the Relay implementation. 
```
2024-08-01 22:42:18.109 [DEBUG] [.internal.devices.bridge.LongPolling] - Long poll response: {"result":[{"deleted":true,"@type":"Dev
iceServiceData","id":"ElectricalFaults","deviceId":"hdm:ZigBee:30fb10fffe46d732"}],"jsonrpc":"2.0"}

2024-08-01 22:42:18.111 [WARN ] [mmon.WrappedScheduledExecutorService] - Scheduled runnable ended with an exception:
java.lang.NullPointerException: Cannot invoke "com.google.gson.JsonElement.getAsString()" because the return value of "com.google.gs
on.JsonObject.get(String)" is null
        at org.openhab.binding.boschshc.internal.serialization.BoschServiceDataDeserializer.deserialize(BoschServiceDataDeserializer
.java:52) ~[?:?]
        at org.openhab.binding.boschshc.internal.serialization.BoschServiceDataDeserializer.deserialize(BoschServiceDataDeserializer
.java:1) ~[?:?]
        at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:76) ~[?:?]
        at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:40) ~[?:?]
        at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:82) ~[?:?]
        at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:61) ~[?:?]
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.readIntoField(ReflectiveTypeAdapterFactory.java:212) ~[?:?]
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$FieldReflectionAdapter.readField(ReflectiveTypeAdapterFactory.
java:433) ~[?:?]
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:393) ~[?:?]
        at com.google.gson.Gson.fromJson(Gson.java:1227) ~[?:?]
        at com.google.gson.Gson.fromJson(Gson.java:1137) ~[?:?]
        at com.google.gson.Gson.fromJson(Gson.java:1047) ~[?:?]
        at com.google.gson.Gson.fromJson(Gson.java:982) ~[?:?]
        at org.openhab.binding.boschshc.internal.devices.bridge.LongPolling.handleLongPollResponse(LongPolling.java:218) ~[?:?]
        at org.openhab.binding.boschshc.internal.devices.bridge.LongPolling.onLongPollComplete(LongPolling.java:196) ~[?:?]
        at org.openhab.binding.boschshc.internal.devices.bridge.LongPolling$1.lambda$0(LongPolling.java:169) ~[?:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
        at java.lang.Thread.run(Thread.java:840) [?:?]
```

**Comment by david-pace** [comment]
The particular bug you reported only happens if the `@type` property is `DeviceServiceData` and no `path` is present. But I also fixed other places where a similar bug could theoretically occur if certain properties are absent.

To verify if the particular bug you reported was fixed, it should be enough to delete / add the device once or twice. You should then see a same or similar debug log entry like

```
2024-07-28 20:01:38.220 [DEBUG] [.internal.devices.bridge.LongPolling] - Long poll response: {"result":[{"deleted":true,"@type":"Dev
iceServiceData","id":"CommunicationQuality","deviceId":"hdm:ZigBee:30fb10fffe46d732"}],"jsonrpc":"2.0"}
```

and then **no** stacktrace with the `NullPointerException` anymore. Of course it's even better if you let the system running for a few days to verify that no other issues occur.

**Comment by mike-bike** [comment]
Hi @david-pace, I will do some tests as advised. Though, please note, that I have not observed any issues with the latest relay version of the JAR. No sight of `NullPointerException`. Would I need to have the deleted device added as a thing? This is the trace with that JAR when deleting the relay:

```
2024-08-03 18:33:43.237 [DEBUG] [.internal.devices.bridge.LongPolling] - Long poll response: {"result":[{"deleted":true,"@type":"DeviceServiceData","id":"ElectricalFaults","deviceId":"hdm:ZigBee:30fb10fffe46d732"}],"jsonrpc":"2.0"}

2024-08-03 18:33:43.239 [DEBUG] [nternal.devices.bridge.BridgeHandler] - Got update for service ElectricalFaults of type DeviceServiceData: null
2024-08-03 18:33:43.240 [DEBUG] [.internal.devices.bridge.LongPolling] - Sending long poll request
2024-08-03 18:33:43.241 [TRACE] [ernal.devices.bridge.BoschHttpClient] - Create request for http client BoschHttpClient@1a77c93{STARTED}
2024-08-03 18:33:43.241 [TRACE] [ernal.devices.bridge.BoschHttpClient] - create request for https://192.168.2.61:8444/remote/json-rpc and content {"jsonrpc":"2.0","method":"RE/longPoll","params":["ffcken954-19","20"]}
2024-08-03 18:33:44.197 [DEBUG] [.internal.devices.bridge.LongPolling] - Long poll response: {"result":[{"deleted":true,"@type":"device","supportedProfiles":[],"id":"hdm:ZigBee:30fb10fffe46d732#1","deviceServiceIds":[],"childDeviceIds":[],"status":"UNDEFINED"}],"jsonrpc":"2.0"}

2024-08-03 18:33:44.199 [DEBUG] [.internal.devices.bridge.LongPolling] - Sending long poll request
2024-08-03 18:33:44.204 [TRACE] [ernal.devices.bridge.BoschHttpClient] - Create request for http client BoschHttpClient@1a77c93{STARTED}
2024-08-03 18:33:44.205 [TRACE] [ernal.devices.bridge.BoschHttpClient] - create request for https://192.168.2.61:8444/remote/json-rpc and content {"jsonrpc":"2.0","method":"RE/longPoll","params":["ffcken954-19","20"]}
2024-08-03 18:33:44.257 [DEBUG] [.internal.devices.bridge.LongPolling] - Long poll response: {"result":[{"deleted":true,"@type":"device","supportedProfiles":[],"id":"hdm:ZigBee:30fb10fffe46d732","deviceServiceIds":[],"childDeviceIds":[],"status":"UNDEFINED"},{"deleted":true,"@type":"message","flags":[],"arguments":{},"id":"b893b2f0-0291-4de3-bfb5-66bbebb04f1d","timestamp":0}],"jsonrpc":"2.0"}

2024-08-03 18:33:44.259 [DEBUG] [.internal.devices.bridge.LongPolling] - Sending long poll request
2024-08-03 18:33:44.259 [TRACE] [ernal.devices.bridge.BoschHttpClient] - Create request for http client BoschHttpClient@1a77c93{STARTED}
2024-08-03 18:33:44.260 [TRACE] [ernal.devices.bridge.BoschHttpClient] - create request for https://192.168.2.61:8444/remote/json-rpc and content {"jsonrpc":"2.0","method":"RE/longPoll","params":["ffcken954-19","20"]}
```

**Comment by david-pace** [comment]
Hmm I don't understand why the first long poll response does not trigger the bug. The relay JAR does not contain the bugfix for the `NullPointerException`. We have to find out the exact error conditions.

Could you maybe try the following:
* Add the device in the Bosch App and create the thing in openHAB
* Initiate a communication quality check in the Bosch App
* Then delete the device in the Bosch App

Does the `NullPointerException` occur now?

**Comment by david-pace** [comment]
I can confirm that I can provoke the `NullPointerException` with the steps above using a Door/Window contact II. Can you also confirm that the bug is triggered when removing any device (e.g. the relay) after having triggered a communication quality check? And does the `NullPointerException` disappear when installing the `-longpoll` JAR I provided?

**Comment by mike-bike** [comment]
Hi @david-pace, I followed your advice but was **not able** to reproduce the `NullPointerException` issue with your latest relay JAR as of Jul-30:

`257 │ Active │  80 │ 4.3.0.202407300453    │ openHAB Add-ons :: Bundles :: Bosch Smart Home Binding`

I have then loaded an old version of the Bosch Binding from March where we had tested the dimmer. With that, I was able to reproduce the issue when deleting the dimmer from Bosch App. 
```
2024-08-04 18:29:17.294 [TRACE] [ernal.devices.bridge.BoschHttpClient] - create request for https://192.168.2.61:8444/remote/json-rpc and content {"jsonrpc":"2.0","method":"RE/longPoll","params":["ffcken954-31","20"]}
2024-08-04 18:29:31.771 [DEBUG] [.internal.devices.bridge.LongPolling] - Long poll response: {"result":[{"deleted":true,"@type":"DeviceServiceData","id":"CommunicationQuality","deviceId":"hdm:ZigBee:60b647fffe14a1e1"}],"jsonrpc":"2.0"}

2024-08-04 18:29:31.778 [WARN ] [mmon.WrappedScheduledExecutorService] - Scheduled runnable ended with an exception:
java.lang.NullPointerException: Cannot invoke "com.google.gson.JsonElement.getAsString()" because the return value of "com.google.gson.JsonObject.get(String)" is null
```

I Have then loaded load long-poll fix and did the same - no `NullPointerException`, all seems to be fine.

```
2024-08-04 19:44:38.922 [TRACE] [ernal.devices.bridge.BoschHttpClient] - create request for https://192.168.2.61:8444/remote/json-rp
c and content {"jsonrpc":"2.0","method":"RE/longPoll","params":["ffcken954-32","20"]}
2024-08-04 19:44:39.002 [DEBUG] [.internal.devices.bridge.LongPolling] - Long poll response: {"result":[{"deleted":true,"@type":"rem
inderActuator","groupId":"intrusion:visual","id":"hdm:ZigBee:60b647fffe14a1e1"},{"deleted":true,"@type":"device","supportedProfiles"
:[],"id":"hdm:ZigBee:60b647fffe14a1e1","deviceServiceIds":[],"childDeviceIds":[],"status":"UNDEFINED"},{"sourceId":"roomLightControl
_hz_16","sourceType":"DEVICE","@type":"message","flags":["STATUS","STICKY"],"messageCode":{"name":"DEVICE_UNAVAILABLE","category":"W
ARNING"},"location":"unused","arguments":{"deviceModel":"HUE_LIGHT_ROOM_CONTROL"},"id":"ddc207a7-a701-4919-80c5-0a740379d502","sourc
eName":"RoomLightControl","timestamp":1722793477562}],"jsonrpc":"2.0"}
```

Not sure if it really addressed the issue. I will try to remember that deleting a Bosch device could generate issues with the binding. Whenever I see no further updates on Bosch devices I could at least check the log...
As the NullPointerException will come with WARN, I could safely reduce the verbosity on my prod box.

Please let me know, when I could get a combined version with all fixes in a JAR. I am happy to install that on my PROD box and monitor the behavior.

Note: While testing with the Dimmer device, I have found an issue when reducing the light level quickly down to zero in the Bosch App. This is the only way to shut off the light with the dimmer app, but the thing does not seem to get the 0% as latest update. I am going to raise another _observation_ for that.

Again, many thanks for all your effort supporting the latest devices!

Regards,
Michael

**Comment by david-pace** [comment]
Hmm maybe I unintentionally fixed the issue partially while developing the relay support 😉

Anyways, if the issue is present in the `4.2.0` release and fixed with the test JAR, we should be fine 👍

The [JAR](http://davidpace.de/openhab/org.openhab.binding.boschshc-4.3.0-SNAPSHOT-longpoll.jar) now contains both the relay support and the long poll fix. It would be great if you could install it on your machine to get some long term verification.

**Comment by mike-bike** [comment]
Sometimes problems solve themselves... 😉

I have loaded the new JAR to my test box and will apply it to prod soon. Will keep you posted.

PS: If we continue to develop and test, I may have justification to consider another PI4 to finally send my PI2 to rest ...
