### ISSUE TITLE
[mielecloud] SSE payload is not valid Json

### ISSUE THREAD

**Issue by LukasA83** [openhab/openhab-addons#19315]
## Expected Behavior

Miele devices are online and reporting data.

## Current Behavior

Miele bridge is online, devices are offline, logs indicate "SSE payload is not valid Json". Json stated in the logs validates properly with Jsonlint.

## Possible Solution

No solution known.

## Steps to Reproduce (for Bugs)

1. Create miele bridge
2. Add miele device
3. Device stays offline

## Your Environment

* Version used: (e.g., openHAB and add-on versions)
* Environment name and version (e.g. Chrome 76, Java 8, Node.js 12.9, ...):
* Operating System and version (desktop or mobile, Windows 10, Raspbian Buster, ...):
Openhab 5.0.1 release build on docker raspi 4.

**Comment by jlaur** [comment]
Logs available here: https://community.openhab.org/t/did-the-miele-api-change/166219

**Comment by jlaur** [comment]
@BjoernLange - FYI.

**Comment by dandjo** [comment]
Here's the payload I am receiving (3 appliances), the log tells me to be invalid. Validation says it's valid. 🤷‍♂️

```json
[
  {
    "000177606469": {
      "ident": {
        "type": {
          "key_localized": "Gerätetyp",
          "value_raw": 2,
          "value_localized": "Trockner"
        },
        "deviceName": "",
        "protocolVersion": 4,
        "deviceIdentLabel": {
          "fabNumber": "000177606469",
          "fabIndex": "41",
          "techType": "TWC560WP",
          "matNumber": "11819560",
          "swids": [
            "5678",
            "25359",
            "25360",
            "20559",
            "25277",
            "5136",
            "20445",
            "25234",
            "4657"
          ]
        },
        "xkmIdentLabel": {
          "techType": "EK037",
          "releaseVersion": "04.05"
        }
      },
      "state": {
        "ProgramID": {
          "value_raw": 2,
          "value_localized": "Baumwolle",
          "key_localized": "Programmbezeichnung"
        },
        "status": {
          "value_raw": 5,
          "value_localized": "In Betrieb",
          "key_localized": "Status"
        },
        "programType": {
          "value_raw": 3,
          "value_localized": "Automatikprogramm",
          "key_localized": "Programmart"
        },
        "programPhase": {
          "value_raw": 514,
          "value_localized": "Trocknen",
          "key_localized": "Programmphase"
        },
        "remainingTime": [0, 21],
        "startTime": [0, 0],
        "targetTemperature": [
          {"value_raw": -32768, "value_localized": null, "unit": "Celsius"},
          {"value_raw": -32768, "value_localized": null, "unit": "Celsius"},
          {"value_raw": -32768, "value_localized": null, "unit": "Celsius"}
        ],
        "coreTargetTemperature": [
          {"value_raw": -32768, "value_localized": null, "unit": "Celsius"}
        ],
        "temperature": [
          {"value_raw": -32768, "value_localized": null, "unit": "Celsius"},
          {"value_raw": -32768, "value_localized": null, "unit": "Celsius"},
          {"value_raw": -32768, "value_localized": null, "unit": "Celsius"}
        ],
        "coreTemperature": [
          {"value_raw": -32768, "value_localized": null, "unit": "Celsius"}
        ],
        "signalInfo": false,
        "signalFailure": false,
        "signalDoor": false,
        "remoteEnable": {
          "fullRemoteControl": true,
          "smartGrid": false,
          "mobileStart": false
        },
        "ambientLight": null,
        "light": null,
        "elapsedTime": [0, 54],
        "spinningSpeed": {
          "unit": "U/min",
          "value_raw": null,
          "value_localized": null,
          "key_localized": "Schleuderdrehzahl"
        },
        "dryingStep": {
          "value_raw": 0,
          "value_localized": "Extratrocken",
          "key_localized": "Trockenstufe"
        },
        "ventilationStep": {
          "value_raw": null,
          "value_localized": "",
          "key_localized": "Lüfterstufe"
        },
        "plateStep": [],
        "ecoFeedback": {
          "currentWaterConsumption": {"unit": "l", "value": 0.0},
          "currentEnergyConsumption": {"unit": "kWh", "value": 0.3},
          "waterForecast": 0.0,
          "energyForecast": 0.9
        },
        "batteryLevel": null
      }
    }
  },
  {
    "000185806322": {
      "ident": {
        "type": {
          "key_localized": "Gerätetyp",
          "value_raw": 1,
          "value_localized": "Waschmaschine"
        },
        "deviceName": "",
        "protocolVersion": 4,
        "deviceIdentLabel": {
          "fabNumber": "000185806322",
          "fabIndex": "32",
          "techType": "WWG360",
          "matNumber": "11333560",
          "swids": [
            "6456",
            "20456",
            "25213",
            "25191",
            "25446",
            "25205",
            "25447",
            "25319"
          ]
        },
        "xkmIdentLabel": {
          "techType": "EK057",
          "releaseVersion": "08.32"
        }
      },
      "state": {
        "ProgramID": {
          "value_raw": 0,
          "value_localized": "",
          "key_localized": "Programmbezeichnung"
        },
        "status": {
          "value_raw": 1,
          "value_localized": "Aus",
          "key_localized": "Status"
        },
        "programType": {
          "value_raw": 0,
          "value_localized": "",
          "key_localized": "Programmart"
        },
        "programPhase": {
          "value_raw": 0,
          "value_localized": "",
          "key_localized": "Programmphase"
        },
        "remainingTime": [0, 0],
        "startTime": [0, 0],
        "targetTemperature": [
          {"value_raw": -32768, "value_localized": null, "unit": "Celsius"},
          {"value_raw": -32768, "value_localized": null, "unit": "Celsius"},
          {"value_raw": -32768, "value_localized": null, "unit": "Celsius"}
        ],
        "coreTargetTemperature": [
          {"value_raw": -32768, "value_localized": null, "unit": "Celsius"}
        ],
        "temperature": [
          {"value_raw": -32768, "value_localized": null, "unit": "Celsius"},
          {"value_raw": -32768, "value_localized": null, "unit": "Celsius"},
          {"value_raw": -32768, "value_localized": null, "unit": "Celsius"}
        ],
        "coreTemperature": [
          {"value_raw": -32768, "value_localized": null, "unit": "Celsius"}
        ],
        "signalInfo": false,
        "signalFailure": false,
        "signalDoor": false,
        "remoteEnable": {
          "fullRemoteControl": true,
          "smartGrid": false,
          "mobileStart": false
        },
        "ambientLight": null,
        "light": null,
        "elapsedTime": [0, 0],
        "spinningSpeed": {
          "unit": "U/min",
          "value_raw": null,
          "value_localized": null,
          "key_localized": "Schleuderdrehzahl"
        },
        "dryingStep": {
          "value_raw": null,
          "value_localized": "",
          "key_localized": "Trockenstufe"
        },
        "ventilationStep": {
          "value_raw": null,
          "value_localized": "",
          "key_localized": "Lüfterstufe"
        },
        "plateStep": [],
        "ecoFeedback": null,
        "batteryLevel": null
      }
    }
  },
  {
    "000106022161": {
      "ident": {
        "type": {
          "key_localized": "Gerätetyp",
          "value_raw": 7,
          "value_localized": "Geschirrspüler"
        },
        "deviceName": "",
        "protocolVersion": 4,
        "deviceIdentLabel": {
          "fabNumber": "000106022161",
          "fabIndex": "65",
          "techType": "G7465",
          "matNumber": "11885020",
          "swids": [
            "5418",
            "20492",
            "25166",
            "25293",
            "25386",
            "4875",
            "20366",
            "20462",
            "4928",
            "20475",
            "25266"
          ]
        },
        "xkmIdentLabel": {
          "techType": "EK057",
          "releaseVersion": "08.32"
        }
      },
      "state": {
        "ProgramID": {
          "value_raw": 0,
          "value_localized": "",
          "key_localized": "Programmbezeichnung"
        },
        "status": {
          "value_raw": 1,
          "value_localized": "Aus",
          "key_localized": "Status"
        },
        "programType": {
          "value_raw": 0,
          "value_localized": "",
          "key_localized": "Programmart"
        },
        "programPhase": {
          "value_raw": 0,
          "value_localized": "",
          "key_localized": "Programmphase"
        },
        "remainingTime": [0, 0],
        "startTime": [0, 0],
        "targetTemperature": [
          {"value_raw": -32768, "value_localized": null, "unit": "Celsius"},
          {"value_raw": -32768, "value_localized": null, "unit": "Celsius"},
          {"value_raw": -32768, "value_localized": null, "unit": "Celsius"}
        ],
        "coreTargetTemperature": [
          {"value_raw": -32768, "value_localized": null, "unit": "Celsius"}
        ],
        "temperature": [
          {"value_raw": -32768, "value_localized": null, "unit": "Celsius"},
          {"value_raw": -32768, "value_localized": null, "unit": "Celsius"},
          {"value_raw": -32768, "value_localized": null, "unit": "Celsius"}
        ],
        "coreTemperature": [
          {"value_raw": -32768, "value_localized": null, "unit": "Celsius"}
        ],
        "signalInfo": false,
        "signalFailure": false,
        "signalDoor": false,
        "remoteEnable": {
          "fullRemoteControl": true,
          "smartGrid": false,
          "mobileStart": false
        },
        "ambientLight": null,
        "light": null,
        "elapsedTime": [0, 0],
        "spinningSpeed": {
          "unit": "U/min",
          "value_raw": null,
          "value_localized": null,
          "key_localized": "Schleuderdrehzahl"
        },
        "dryingStep": {
          "value_raw": null,
          "value_localized": "",
          "key_localized": "Trockenstufe"
        },
        "ventilationStep": {
          "value_raw": null,
          "value_localized": "",
          "key_localized": "Lüfterstufe"
        },
        "plateStep": [],
        "ecoFeedback": null,
        "batteryLevel": null
      }
    }
  }
]
```

**Comment by jgeraerts** [comment]
This change fixes the problem for me. The only thing I don't really know if miele inadvertently changed the api and will roll the change back.

**Comment by LevinXX** [comment]
It seems Miele released a new version today, which should also support new generation devices (like my washing machine ;-))
Maybe the changes were made because of this.
[https://developer.miele.com/docs/release-notes#_12-september-2025](url)

**Comment by dandjo** [comment]
What's interesting is that the documentation still lists the old version. Perhaps a JSON library or a parameter in the serializer has been changed and/or the change is unknown? Maybe we should contact them?

https://developer.miele.com/docs/swagger

**Comment by jgeraerts** [comment]
But either the documentation hasn't been updated yet because it still states that the eventing api returns the same objects as the `/devices` call which does not start with a `list` but rather device id mapped to the device spec. 

I think it's an unintended change.

**Comment by dandjo** [comment]
Yes, that's what I meant. I also think this is a bug on Miele side.

**Comment by jgeraerts** [comment]
I'll contact developer@miele.com. No idea though how responsive they are.

**Comment by jgeraerts** [comment]
within homeassistant they have the issue obviously as well. There they state miele confirmed the issue and are working on a fix. 

https://github.com/home-assistant/core/issues/152104#issuecomment-3280369209

**Comment by ThomasM102** [comment]
I've installed the PR in my openhab 5.0.1. The parse error is gone, but my dishwasher's status is no longer updated. Disabling/enabling the bridge updates the status. Is anyone else having this problem?

**Comment by astrandb** [comment]
Miele developers are obviously changing things back and forth. The SSE data was reverted to a dict for a couple of hours, now it is back to list...
The event stream is not updating here either.

**Comment by ThomasM102** [comment]
Thanks, then I guess I'll have to wait until Miele has reached a final decision.

**Comment by grmpf72** [comment]
Is there any possibility to get the nightlly jar file (5.1.0) into openhab 4.3.5?

**Comment by ThomasM102** [comment]
Why ? Currently, there is no solution to this problem in any version. There can't be one until Miele stops its unprofessional tinkering with the API.

**Comment by grmpf72** [comment]
I found a nightly jar file for the miele cloud for version 5.1.0 dd/ Sep/14 and thought, that the solution for this issue ist implemented there.
I'm not very experienced! Can I fix the problem temporarily by replacing DeviceCollection.java anywhere? If yes, where and how?

**Comment by ThomasM102** [comment]
Every night, the nightly build creates new jar files of all bindings. This doesn't mean that anything in them has been fixed. As I said, there is currently no solution, and there won't be one until Miele provides a final API. Only then can the binding be adapted. I have currently deactivated my Miele binding.

**Comment by grmpf72** [comment]
> Every night, the nightly build creates new jar files of all bindings. This doesn't mean that anything in them has been fixed. As I said, there is currently no solution, and there won't be one until Miele provides a final API. Only then can the binding be adapted. I have currently deactivated my Miele binding.

so did I. So let's wait...

**Comment by robkamp** [comment]
Seems the API has moved to 

<img width="513" height="62" alt="Image" src="https://github.com/user-attachments/assets/5a07dd69-8d70-47d7-8e22-946b4e54b58f" />

And is using a new OAuth2 authentication. I use my Miele OAuth2 token on https://api.mcs3.miele.com/thirdparty/ using their swagger page at https://developer.miele.com/docs/swagger and I got an answer.

**Comment by jgeraerts** [comment]
After a few days of 504 errors around 16h CEST things seem to be operational again. 🤞

**Comment by grmpf72** [comment]
Do I have to do something special? I still get the 504 error and the message OAuth2-Access-Token not configuered.

**Comment by jgeraerts** [comment]
For me it just started working again.

**Comment by grmpf72** [comment]
Status: "Connection pending",
Log: [oauth2client.internal.OAuthConnector] - grant type refresh_token to URL https://api.mcs3.miele.com/thirdparty/token failed with error code invalid_grant, description

That's it.

**Comment by grmpf72** [comment]
OK, I paired it again as described in the Binding-Doc and now it works again!  Thank you!

**Comment by dandjo** [comment]
Confirmed: working again. So I guess this was solved by Miele and we can close this ticket?
