### ISSUE TITLE
Use Apache Karaf as a runtime container

### ISSUE THREAD

**Issue by kaikreuzer** [openhab/openhab-addons#194]

**Comment by kaikreuzer** [comment]
Using Apache Karaf would bring a couple of features for openHAB:
- stable management scripts that also allow integration as a system service (e.g. on Windows or Linux)
- Integration with other OSGi-based applications such as Apache Camel, CXF and ActiveMQ
- provisioning through Karaf archives, so we could install addons from a remote repo easily.

Possible risks of this move:
- Karaf does not use logback for logging, so the logger implementation would change
- The size of the runtime increases as Karaf is not modular and comes with a lot of stuff which we would not need (e.g. Blueprint). This might be contra-productive on small systems like a RasPi 1.
- Having multi-instance possibilities and many console commands (which are different to the existing ones from Equinox) may make things more complicated for "regular" openHAB users.
- We are between the two worlds of Eclipse Equinox and Apache Felix - this might lead to unexpected problems.

If any expert on Karaf could comment on these risks, it would be great :-)

**Comment by watou** [comment]
I for one would like to see OH2 running in Karaf.  While I'm no Karaf expert, I use it for Camel and I find it very easy to monitor and manage remotely.  The only reason I can think of to _not_ switch is if it expands the memory footprint more than a trivial amount, as there is already an uncomfortable size gap between OH1 and dedicated systems like Vera.

**Comment by maggu2810** [comment]
As I am already using Karaf for OH2 I prefer to support it mainline, too. ;-)

**Comment by kaikreuzer** [comment]
@maggu2810 Do you have any opinion about the concern of an increasing size and thus higher performance requirements? Does it e.g. still run on a RaspPi1?

**Comment by maggu2810** [comment]
Never tested it with a RespPi1.
If we use an "empty" Karaf framework, just using the stuff Karaf needs to
work, this should be the size the memory footprint increases.
Do you concern, that Karaf adds a lot of management information to every
bundle, so the memory footprint of every bundle increases?

2015-04-29 11:17 GMT+02:00 Kai Kreuzer <notifications@github.com>:

**Comment by kaikreuzer** [comment]
> Do you concern, that Karaf adds a lot of management information to every
bundle, so the memory footprint of every bundle increases?

No, I don't think (hope!) that there will be any additional overhead per bundle - my concern is only the "base" that is added as Karaf has Spring/Blueprint as a mandatory part and a few other components that I think are not really relevant for an openHAB container, but cannot be removed from Karaf, so it feels like some unnecessary ballast.

**Comment by hakan42** [comment]
From karaf.apache.org: 

Logging System: using a centralized logging back end supported by Log4J, Karaf supports a number of different APIs (JDK 1.4, JCL, SLF4J, Avalon, Tomcat, OSGi)

I seriously hope that we can bolt SLF4j underneath karaf as I would love to ship my OpenHab logs to a logstash server.

**Comment by kaikreuzer** [comment]
What I said is

> Karaf does not use logback for logging, so the logger implementation would change

slf4j is the API, logback and log4j two possible logger implementations. openHAB currently uses logback and as far as I understand Karaf uses log4j.

**Comment by oliverlietz** [comment]
I'm interested in openHAB on Karaf/RasPi2. Karaf 4 will be released soon: [_The 4.0.x line will ship with OSGi Rev5 support via Felix 4.4.1 and Equinox 3.9.1-v20140110-1610, and a completely refactored internal framework without Blueprint for internal usage. From a users point of view these changes will yield a smaller, more efficient Karaf core._](https://karaf.apache.org/index/community/download/karaf-4.0.0.M2-release.html)

**Comment by kaikreuzer** [comment]
Yes, I am already using 4.0.0M2 and waiting for M3 to be released soon. That Blueprint is optional now is a good thing!

**Comment by oliverlietz** [comment]
Can you provide a quickstart guide and/or Karaf Feature (compiling my own right now for use with EnOcean) to get SmartHome/openHAB up and running on Karaf? I've some spare time and would like to see openHAB, Karaf, RasPi 1/2, EnOcean Pi 868/EnOcean USB 300 and my PEHA Easyclick devices playing together finally.

**Comment by kaikreuzer** [comment]
@oliverlietz you have spare time? Sounds fantastic as I am currently struggling with Karaf and not getting much further...
You can have a look at my current state of things here: https://github.com/kaikreuzer/openhab2/tree/karaf.

In there, I have replaced the whole p2 feature build by one KAR: https://github.com/kaikreuzer/openhab2/tree/karaf/features/
This currently only includes one Karaf feature with only one bundle - this needs to be of course extended to include everything relevant.
In https://github.com/kaikreuzer/openhab2/tree/karaf/distribution/karaf I am trying to build a custom Karaf distribution, but so far I failed to include my own resources in src/main/resources.
In https://github.com/kaikreuzer/openhab2/tree/karaf/distribution/downloads, I want to assemble a final distributable - I actually plan to have Karaf within the "runtime" subfolder there, so that the openHAB user is not directly exposed to Karaf. But also on here I didn't yet succeed in extracting the custom Karaf distro into the right place.
So if you have any chance to help on these things, it would be great!

**Comment by kaikreuzer** [comment]
Btw, my goal is to have quite finegrained features, so that every addon can be installed as a feature individually as well as things like MQTT support, the Paper UI, HABmin, etc.

**Comment by maggu2810** [comment]
> In https://github.com/kaikreuzer/openhab2/tree/karaf/distribution/karaf I am trying to build a custom Karaf distribution, but so far I failed to include my own resources in src/main/resources.

I changed your project pom to use Karaf 4.0.0.M2 instead of 4.0.0-SNAPSHOT (karaf.version).
The stuff of src/main/resources is used (the feature xmls, branding file in etc, ...) but e.g. config.properties seems to be overwritten again.
* .../distribution/karaf/target/assembly contains the normal karaf stuff
* .../distribution/karaf/target/classes contains the resources
So, perhaps we need to change who win, if a file is available in both locations.

Will have a brief look, if I found something that could help.

**Comment by maggu2810** [comment]
IMHO this is the related issue:
http://karaf.922171.n3.nabble.com/karaf-assembly-and-config-files-td4032040.html

**Comment by kaikreuzer** [comment]
> I changed your project pom to use Karaf 4.0.0.M2 instead of 4.0.0-SNAPSHOT (karaf.version).

I switched from M2 to SNAPSHOT because of http://mail-archives.apache.org/mod_mbox/karaf-user/201504.mbox/%3C551E8912.1030006@imag.fr%3E: 
2. The generated distribution archives have very fancy names: 
pom.xml.tar.gz or pom.xml.zip! Apart from that, the content of the 
distribution is just fine. I don't know if the configuration for 
maven-karaf-plugin has changed, BUT this specific issue seems to be 
solved in the trunk version: distributions names are back to normal (cf. 
B.2).

**Comment by maggu2810** [comment]
You could try that one: https://github.com/kaikreuzer/openhab2/compare/karaf...maggu2810:karaf
The config.properties is your one.

**Comment by maggu2810** [comment]
Wait a moment... ;-)

You have written:

> In https://github.com/kaikreuzer/openhab2/tree/karaf/distribution/karaf I am trying to build a custom Karaf distribution, but so far I failed to include my own resources in src/main/resources.

and you have written:

> I switched from M2 to SNAPSHOT because of ... the content of the distribution is just fine.

So, is the problem (config.properties of resources is overwritten by config.properties of karaf) already solved if you are using the SNAPSHOT?

**Comment by kaikreuzer** [comment]
Are you sure that the 
```
	<resources>
		<resource>
			<directory>${basedir}/target/assembly</directory>
		</resource>
	</resources>
```
is required? That does not seem to make much sense...

**Comment by kaikreuzer** [comment]
> and you have written: "... the content of the distribution is just fine."

No, this wasn't me, that was someone else reporting the problem about the pom.xml.zip filename.

> So, is the problem (config.properties of resources is overwritten by config.properties of karaf) already solved if you are using the SNAPSHOT?

No, it isn't.

**Comment by maggu2810** [comment]
> Are you sure that the ... is required?

I just tried to get a workaround for the problem and pushed it, so you can test it.
The intention was not to create a cleaned up commit that could be merged.
First I want to know, if your first problem could be solved.

**Comment by maggu2810** [comment]
Yes, the lines are required to prevent creation of target/classes.

**Comment by maggu2810** [comment]
Feels very hackish.

**Comment by oliverlietz** [comment]
I'm maintaining [Sling's Karaf Features](https://github.com/apache/sling/blob/trunk/contrib/launchpad/karaf/org.apache.sling.launchpad.karaf-features/src/main/feature/feature.xml) and have something similar in mind for my SmartHome/openHAB features - so features first, custom distribution second.

I had to set version of `org.osgi.service.http` in Dashboard UI's `MANIFEST.MF` to `1.2.0` (was `1.2.1`) to start in K4M2. Any reason why it is `1.2.1`?

The last time I played with openHAB was in 2013. Is the EnOcean support now useable? Any hints to get quick results? Seeing/receiving signals from my switches in openHAB connected to EnOcean Pi 868/EnOcean USB 300 would be sufficient.

**Comment by kaikreuzer** [comment]
> I'm maintaining Sling's Karaf Features and have something similar in mind for my SmartHome/openHAB features - so features first

Sounds good - having someone with experience defining the features is great! Btw, what do you think: Should we also define Karaf features on the Eclipse SmartHome side (such as "esh-core", "esh-rest", "esh-dsl" etc. and include them in openHAB 2 features? Or would you suggest to define all of them only within openHAB for the moment?

> I had to set version of org.osgi.service.http in Dashboard UI's MANIFEST.MF to 1.2.0 (was 1.2.1) to start in K4M2. Any reason why it is 1.2.1?

Not at all, I have removed it now: https://github.com/openhab/openhab2/commit/a80279079d7da5d4b39092b8d3ddf1100350e019

> Is the EnOcean support now useable?

It works pretty well with the 1.x EnOcean binding through the compat layer - I am using it myself regularly for demos with the PTM210. But better ask @maggu2810, he is the better expert for EnOcean :-)

**Comment by kaikreuzer** [comment]
> IMHO this is the related issue:
http://karaf.922171.n3.nabble.com/karaf-assembly-and-config-files-td4032040.html

Indeed - unfortunately, there is no solution... Thanks for posting the problem at https://issues.apache.org/jira/browse/KARAF-2742

**Comment by maggu2810** [comment]
> Should we also define Karaf features on the Eclipse SmartHome side (such as "esh-core", "esh-rest", "esh-dsl" etc. and include them in openHAB 2 features?

I think we should have a look at the overhead to maintain that all. At the moment there are still some difference between Tycho and the Eclipse IDE (at least for the karaf console bundle).
Personally I would like to have such features but perhaps we could solve this for OH2 first and then have a look at ESH...

> But better ask @maggu2810, he is the better expert for EnOcean

@oliverlietz, We should not mix the topics in this issue. Contact me if you want some information, my email address should be visible.

> Indeed - unfortunately, there is no solution... 

Doesn't the very ugly workaround / hack (filtered resources, ...) work for you?

> Thanks for posting the problem at

You're welcome.

**Comment by kaikreuzer** [comment]
> Doesn't the very ugly workaround / hack (filtered resources, ...) work for you?

No, I tried it with the pom given in the issue. My files end up in target/classes, but they are not packaged into the tar...

**Comment by maggu2810** [comment]
<pre>
$ pushd distribution/karaf

$ rm -rf target; mvn clean install
BUILD SUCCESS

$ ls -1 target/
assembly
org.openhab.distribution.karaf-2.0.0-SNAPSHOT.tar.gz
org.openhab.distribution.karaf-2.0.0-SNAPSHOT.zip

$ tar xOvzf target/org.openhab.distribution.karaf-2.0.0-SNAPSHOT.tar.gz org.openhab.distribution.karaf-2.0.0-SNAPSHOT/etc/config.properties | grep "karaf.framework="
org.openhab.distribution.karaf-2.0.0-SNAPSHOT/etc/config.properties
karaf.framework=equinox
</pre>

**Comment by maggu2810** [comment]
* I could start the unpacked karaf instance but "your" feature is not installed.
* Have to add a change to the feature xml (remove resolver attribute).
* Now the feature will be installed
* The boot feature cannot be installed, so the karaf bootup hangs, this is a problem of the feature configuration.

So, the dependencies of a bootup feature must be resolvable...

<pre>
2015-05-13 09:49:25,812 | ERROR | pool-1-thread-1  | BootFeaturesInstaller            | 7 - org.apache.karaf.features.core - 4.0.0.M2 | Error installing boot features
org.osgi.service.resolver.ResolutionException: Unable to resolve root: missing requirement [root] osgi.identity; osgi.identity=org.openhab.kar; type=karaf.feature; version="[2.0.0.SNAPSHOT,2.0.0.SNAPSHOT]"; filter:="(&(osgi.identity=org.openhab.kar)(type=karaf.feature)(version>=2.0.0.SNAPSHOT)(version<=2.0.0.SNAPSHOT))" [caused by: Unable to resolve org.openhab.kar/2.0.0.SNAPSHOT: missing requirement [org.openhab.kar/2.0.0.SNAPSHOT] osgi.identity; osgi.identity=org.openhab.core; type=osgi.bundle; version="[2.0.0.201505121349,2.0.0.201505121349]"; resolution:=mandatory [caused by: Unable to resolve org.openhab.core/2.0.0.201505121349: missing requirement [org.openhab.core/2.0.0.201505121349] osgi.wiring.package; filter:="(&(osgi.wiring.package=com.google.common.cache)(version>=10.0.1)(!(version>=2147483647.2147483647.2147483647)))"]]
</pre>

**Comment by maggu2810** [comment]
As I started using OH2 with Karaf I created some features that contains the dependencies of ESH and OH2. The dependencies are the bundles of the TP that are necessary in a running instance.

I think we have to create a clean configuration of that features and the bundles should all be found by a Maven repository. I talk about something similar to "org.openhab.kar/src/main/feature/feature.xml" but for bundles that are necessary to use ESH / OH2 at all.

So, if we create an oh2-core feature that contains all bundles of oh2 that are necessary for a minimal runtime, we should also create a oh2-core-external feature that contains all non-oh2 bundles that are necessary to resolve the oh2-core feature.

**Comment by kaikreuzer** [comment]
> Personally I would like to have such features but perhaps we could solve this for OH2 first and then have a look at ESH...

I agree, let's start getting things in place at openHAB 2.

> So, if we create an oh2-core feature that contains all bundles of oh2 that are necessary for a minimal runtime, we should also create a oh2-core-external feature that contains all non-oh2 bundles that are necessary to resolve the oh2-core feature.

So the problem here is to find the non-oh2 in a Maven repo, right? Actually, the ESH build deploys all to Maven repos, so this would only have to be configured accordingly (I could make the build https://openhab.ci.cloudbees.com/job/smarthome/ to deploy the result to a certain location that we could then reference in the openHAB2 build).

@maggu2810, as you have already created such features for yourself, would you want to share them as a starting point?

**Comment by maggu2810** [comment]
> So the problem here is to find the non-oh2 in a Maven repo, right?

Yes, at least exact that one, that are used.

> Actually, the ESH build deploys all to Maven repos

Also the non-ESH artifacts? Which repo you refer? At this one https://repo.eclipse.org/#view-repositories;smarthome-snapshots~browsestorage I found only org.eclipse.smarthome stuff. I only knows about the zip file org.eclipse.smarthome.products/org.eclipse.smarthome.repo that contains the JARs, but this does not help to fetch them using maven.

> I could make the build https://openhab.ci.cloudbees.com/job/smarthome/ to deploy the result to a certain location that we could then reference in the openHAB2 build

This would be great if there is a Maven Repo that all dependencies could be fetched from.

> would you want to share them as a starting point

So, I talked about the old one, you (@kaikreuzer) that you are already using / storing in your fork (https://github.com/kaikreuzer/openhab2/blob/karaf/distribution/karaf/src/main/resources/features/tp-1.0.0-features.xml). As I am changed my solution to use a manager that could keep running instances up to date, the feature XML was not updated anymore.

But if there is a Maven Repo that contains all the dependencies (no more, no less), we could create a feature that contains exactly that one.

**Comment by kaikreuzer** [comment]
> Also the non-ESH artifacts? 

No, of course not, you are absolutely right.

> the zip file org.eclipse.smarthome.products/org.eclipse.smarthome.repo that contains the JARs

We could use this repo together with the zip file org.eclipse.smarthome.products/org.eclipse.smarthome.repo that contains the JARs and we should end up with a local Maven repo that contains all bundles. Could that work?
P.S.: I tried this plugin for directly creating a KAR, but I failed using this KAR within the Karaf custom distribution - that's why I switched to manually define the KAR and use the "official" packaging plugin.

**Comment by maggu2810** [comment]
So, let's collect some information (this is my current opinion, hope that is correct).

# Using Maven to fetch bundles

To fetch the non-ESH + non-OH2 bundles with Maven we need at least the POM.
The most JAR contains their pom, so we could extract it and deploy it to a Maven repo.
But there are bundles that does not contain a pom.
If we want to be able to store them in a Maven Repo, we have to specify at least the group id, artifact id and version.

To resolve that problem I created a new channel aspect for Package Drone, so I could refer all bundles by maven using a fixed (configurable) group id, an artifact id that is identical to the BSN and a version that is equal to the bundle version.

# Use file location to fetch bundles

Another approach would be to use the bundles in "./runtime/server/plugins/" and store them "somewhere" in our karaf distribution. The feature that installs that bundles could use the "file:" uri instead of the Maven (mvn:) one.

# Use kar-packager

I visited this site you linked already a few times (using Google with Karaf and Tycho) but never tried that approach.The fact that the last commit in the Github repo was at "Sep 26, 2012" upset myself. But it sound similar to that one, that I tried to solve with the Package Drone channel aspect.
Perhaps we should try this one.

**Comment by maggu2810** [comment]
Could you create "something" so we get a directory / zip that contains all bundles that are necessary for OH2 to run and no other bundles?
Perhaps we need to exclude stuff later that is already part of our karaf instance (console, OSGi framework, ...).

I tried to create a kar using kar-packager and the directory "./runtime/server/plugins/.
I cannot install this kar ATM caused by missing requirements.
The directory contains "org.eclipse.emf.codegen/2.10.0.v20140519-0339" that need "org.eclipse.jdt.core" but that one is missing.
Do we need "org.eclipse.emf.codegen" at runtime?

**Comment by kaikreuzer** [comment]
Yes, that sounds correct. I am definitely against the approach "to use the bundles in "./runtime/server/plugins/"", because this would tie the features to our custom distro and thus could not be used by others on a standard Karaf distro. Therefore I would want to build KARs that can be easily consumed by us and others.

**Comment by kaikreuzer** [comment]
> Do we need "org.eclipse.emf.codegen" at runtime?

I don't think so.

**Comment by kaikreuzer** [comment]
@maggu2810 , @oliverlietz : Just for a bit of planning - do you guys think it is realistic to get the distribution changed to Karaf within the next week? I would clearly need a lot of help as I am a newbie with Karaf and have a tight schedule regarding code reviews of PR for the alpha 2 release. So I am wondering, if we should decide to do the alpha 2 release still with the old structure and go for Karaf afterwards (when there might also be a Karaf 4 final)? What's your opinion?

**Comment by oliverlietz** [comment]
We should go for Karaf afterwards and get the build and features right first. Jean-Baptiste Onofré works on getting the [resource filtering fixed](http://mail-archives.apache.org/mod_mbox/karaf-dev/201505.mbox/%3c5553DF85.4060408@nanthrax.net%3e).

I'm creating two groups of features - one for Eclipse SmartHome and one for openHAB - using Maven coordinates (`<bundle dependency="true">mvn:...`), breaking the features further into smaller ones and deploy to plain Karaf. Did you guys try with Felix instead of Equinox also?

**Comment by kaikreuzer** [comment]
Ok, I removed this issue from the alpha 2 milestone - let's do not rush it, but make it nice.

> Did you guys try with Felix instead of Equinox also?

@maggu2810 used it on Felix and afaik it worked in general. Nonetheless, there seem to be some issues which might have to be analyzed (see e.g. https://github.com/openhab/openhab2/issues/224#issuecomment-99139216). But in general, I would like to reach compatibility with Felix - so feel free to use it and report any bugs that you find.

**Comment by maggu2810** [comment]
I would also prefer to do it after the alpha release.

@oliverlietz I have a set of bundles (lists) to get ESH / OH2 running for Felix and for Equinox. Some of them are already split into smaller parts (e.g. jetty, REST, ...). I could send it to you next week.

Perhaps we could also solve the startup order without using explicit start levels.

**Comment by maggu2810** [comment]
For Felix, not for Equinox (without the OSGi framework selected by Karaf)
* startLevel="41" symbolicName="org.apache.felix.eventadmin" version="1.4.2"
* startLevel="41" symbolicName="org.apache.felix.scr" version="1.8.2"
* startLevel="41" symbolicName="org.osgi.compendium" version="4.1.0"

For Equinox, not for Felix (without the OSGi framework selected by Karaf)
* startLevel="41" symbolicName="org.eclipse.osgi.services" version="3.4.0.v20140312-2051"
* startLevel="41" symbolicName="org.eclipse.equinox.ds" version="1.4.200.v20131126-2331"
* startLevel="41" symbolicName="org.eclipse.equinox.event" version="1.3.100.v20140115-1647"
* startLevel="41" symbolicName="org.eclipse.equinox.util" version="1.0.500.v20130404-1337"

Common
* startLevel="50" symbolicName="org.eclipse.equinox.common" version="3.6.200.v20130402-1505"
* startLevel="51" symbolicName="org.eclipse.equinox.registry" version="3.5.400.v20140428-1507"
* startLevel="51" symbolicName="org.eclipse.equinox.supplement" version="1.5.100.v20140428-1446"
* startLevel="80" symbolicName="com.google.gson" version="2.2.4.v201311231704"
* startLevel="80" symbolicName="com.ibm.icu.base" version="52.1.0.v201404171520"
* startLevel="80" symbolicName="javax.activation" version="1.1.0.v201211130549"
* startLevel="80" symbolicName="javax.mail" version="1.4.0.v201005080615"
* startLevel="80" symbolicName="javax.servlet" version="3.1.0.v20140303-1611"
* startLevel="80" symbolicName="org.apache.commons.codec" version="1.6.0.v201305230611"
* startLevel="80" symbolicName="org.apache.commons.collections" version="3.2.0.v2013030210310"
* startLevel="80" symbolicName="org.apache.commons.exec" version="1.1.0.v201301240602"
* startLevel="80" symbolicName="org.apache.commons.httpclient" version="3.1.0.v201012070820"
* startLevel="80" symbolicName="org.apache.commons.io" version="2.2.0.v201405211200"
* startLevel="80" symbolicName="org.apache.commons.lang" version="2.6.0.v201404270220"
* startLevel="80" symbolicName="org.apache.commons.net" version="3.2.0.v201305141515"
* startLevel="80" symbolicName="org.apache.httpcomponents.httpclient" version="4.2.6.v201311072007"
* startLevel="80" symbolicName="org.apache.httpcomponents.httpcore" version="4.2.5.v201311072007"

RESTful web services
* startLevel="80" symbolicName="com.eclipsesource.jaxrs.jersey-all" version="2.16.1"
* startLevel="80" symbolicName="com.eclipsesource.jaxrs.provider.gson" version="2.1.0.201502151020"
* startLevel="80" symbolicName="com.eclipsesource.jaxrs.publisher" version="4.2.1.201502171315"

EMF, Xtext, Xtend (and requirements)
* startLevel="59" symbolicName="com.google.guava" version="12.0.0"
* startLevel="59" symbolicName="com.google.inject" version="3.0.0.v201312141243"
* startLevel="59" symbolicName="org.antlr.runtime" version="3.2.0.v201101311130"
* startLevel="59" symbolicName="org.objectweb.asm" version="5.0.1.v201404251740"
* startLevel="59" symbolicName="org.eclipse.emf.common" version="2.10.0.v20140514-1158"
* startLevel="59" symbolicName="org.eclipse.emf.ecore" version="2.10.0.v20140514-1158"
* startLevel="59" symbolicName="org.eclipse.emf.ecore.xmi" version="2.10.0.v20140514-1158"
* startLevel="59" symbolicName="org.eclipse.xtend.lib" version="2.6.2.v201407030533"
* startLevel="59" symbolicName="org.eclipse.xtext.common.types" version="2.6.2.v201407030533"
* startLevel="59" symbolicName="org.eclipse.xtext.smap" version="2.6.2.v201407030533"
* startLevel="59" symbolicName="org.eclipse.xtext.util" version="2.6.2.v201407030533"
* startLevel="59" symbolicName="org.eclipse.xtext" version="2.6.2.v201407030533"
* startLevel="59" symbolicName="org.eclipse.xtext.xbase.lib" version="2.6.2.v201407030533"
* startLevel="59" symbolicName="org.eclipse.xtext.xbase" version="2.6.2.v201407030533"

HTTP service
* startLevel="80" symbolicName="org.apache.felix.http.servlet-api" version="1.0.0"
* startLevel="80" symbolicName="org.apache.felix.http.api" version="2.3.0"
* startLevel="80" symbolicName="org.apache.felix.http.base" version="2.3.0"
* startLevel="80" symbolicName="org.apache.felix.http.bridge" version="2.3.0"
* startLevel="80" symbolicName="org.apache.felix.http.jetty" version="2.3.0"
* startLevel="80" symbolicName="org.apache.felix.http.proxy" version="2.3.0"
* startLevel="80" symbolicName="org.apache.felix.http.whiteboard" version="2.3.0"
* startLevel="80" symbolicName="org.apache.felix.http.sslfilter" version="0.1.0"
* startLevel="80" symbolicName="javax.servlet" version="3.0.0.v201112011016"
* startLevel="80" symbolicName="org.eclipse.jetty.util" version="8.1.14.v20131031"
* startLevel="80" symbolicName="org.eclipse.jetty.client" version="8.1.14.v20131031"
* startLevel="80" symbolicName="org.eclipse.jetty.continuation" version="8.1.14.v20131031"
* startLevel="80" symbolicName="org.eclipse.jetty.http" version="8.1.14.v20131031"
* startLevel="80" symbolicName="org.eclipse.jetty.io" version="8.1.14.v20131031"
* startLevel="80" symbolicName="org.eclipse.jetty.jmx" version="8.1.14.v20131031"
* startLevel="80" symbolicName="org.eclipse.jetty.servlet" version="8.1.14.v20131031"
* startLevel="80" symbolicName="org.eclipse.jetty.server" version="8.1.14.v20131031"
* startLevel="80" symbolicName="org.eclipse.jetty.security" version="8.1.14.v20131031"
* startLevel="80" symbolicName="org.eclipse.jetty.webapp" version="8.1.14.v20131031"
* startLevel="80" symbolicName="org.eclipse.jetty.xml" version="8.1.14.v20131031"

jUPnP
* startLevel="80" symbolicName="org.jupnp" version="2.0.0.201502111008"

ESH comments
* using start levels 63, 64 and 65 for the stuff that needs a start level (should be fixed)
* 80 for all remaining bundles

Comments
* it should be possible (good OSGi practice) to stop forcing start levels (but at the moment this does not work)
* need to start org.eclipse.equinox.common before org.eclipse.equinox.registry, see: https://bugs.eclipse.org/bugs/show_bug.cgi?id=357804#c3
* It seems that xtext is using internals (normally not exported stuff of guice (e.g. com/google/inject/internal/MoreTypes.class)

**Comment by maggu2810** [comment]
> I am definitely against the approach "to use the bundles in "./runtime/server/plugins/"", because this would tie the features to our custom distro and thus could not be used by others on a standard Karaf distro. Therefore I would want to build KARs that can be easily consumed by us and others.

Maybe I have my train of thought does not explain enough.

I have already written:
> So, if we create an oh2-core feature that contains all bundles of oh2 that are necessary for a minimal runtime, we should also create a oh2-core-external feature that contains all non-oh2 bundles that are necessary to resolve the oh2-core feature.

The post above should collect some approaches  how we could package all dependencies, regardless of the mechanism there is still the requirement to split the external (non-esh, non-oh2) dependencies and the esh, oh2 bundles / feature sets.

The collection of dependencies will depend on the target solution and could not be hard coded. The concrete solution should decide if e.g. jetty or another http server is used. But for the OH2 system, we could create a kar that contains jetty as this is the target platform for openHAB 2.

So, the usage of "./runtime/server/plugins/" was just an example, but if we every using this one, this would be perhaps oh2-targetplatform.kar that have to be installed on an OH2 system but no other kar will contain a dependency to this one.

I am missing something?

**Comment by oliverlietz** [comment]
I have pushed my initial set of features compiled last week from scratch to [oliverlietz/smarthome](https://github.com/oliverlietz/smarthome).

**Comment by oliverlietz** [comment]
Instead of start levels we should use services or [Provide-Capability](http://wiki.osgi.org/wiki/Provide-Capability)/[Require-Capability](http://wiki.osgi.org/wiki/Require-Capability) to declare requirements.

> startLevel="41" symbolicName="org.osgi.compendium" version="4.1.0"

`org.osgi.*` should never be deployed. The classes are provided by implementations.

**Comment by kaikreuzer** [comment]
> So, the usage of "./runtime/server/plugins/" was just an example, but if we every using this one, this would be perhaps oh2-targetplatform.kar that have to be installed on an OH2 system but no other kar will contain a dependency to this one.
>
> I am missing something?

No, not at all. My point was only that I would not want features that refer to the local filesystem (i.e. to "./runtime/server/plugins/"), but should instead refer to Maven artifacts that can be nicely packaged into KARs.

**Comment by maggu2810** [comment]
Ah, ok, full ack.
As mentioned before, that would be my preferred solutions but so we need a Maven repo that contains all that stuff.

> It seems that xtext is using internals (normally not exported stuff of guice (e.g. com/google/inject/internal/MoreTypes.class)

If I searched for guice with the same version you are using in a public repo, I realized that you are using normally not exported stuff. It seems someone changed the export section of the manifest because Xtext need this.

**Comment by kaikreuzer** [comment]
> we need a Maven repo that contains all that stuff.

That's why I thought that http://eclipsesource.com/blogs/2012/08/22/from-eclipse-tycho-to-apache-karaf-the-easy-way/ could be helpful as it transforms p2 into a Maven repo.

> If I searched for guice with the same version you are using in a public repo, I realized that you are using normally not exported stuff. It seems someone changed the export section of the manifest because Xtext need this.

Yes, it is possible that the bundles on Eclipse Orbit are not identical to what you find on Maven Central - they might be tweaked to work nicely with OSGi.

**Comment by maggu2810** [comment]
We probably mean the same thing...

On your link is written:

> a simple Maven plug-in (strange experience btw.) to build an Apache Karaf Archive (kar) out of a folder containing OSGi bundles

As i written before:

> I tried to create a kar using kar-packager and the directory "./runtime/server/plugins/.

My indention was not to use links to "./runtime/server/plugins/", but using "such" a directory to create the kar.

**Comment by maggu2810** [comment]
Regardless what have been written, read or understood.
Let's look further to solve the problem.

**Comment by maggu2810** [comment]
If played again with all that stuff and need some help about features.
@oliverlietz Perhaps you can give me some hints.

* I added all necessary jar for "a" target platform to a Maven repository (using fixed group id, the BSN for artifact id, and the bundle version as version).
* I have written a tool, that reads the configuration file of a created openHAB 2 product (openhab2/runtime/runtime/server/configuration/config.ini) and extract the information ("osgi.bundles" line) to create a target platform with exact the same bundles and version as the current one.
* The tool is able to create "bundle:install" lines to install all that bundles. That is working and now I have the exact same bundles.
* The tool is able to creaet the "<bundle>" tags for a feature XML (I believe the lines are correct).
* I can create a kar of that XML that contains all the required bundles. So, no problem that the bundles could be resolved using Maven only on my environment. The kar should contain the feature XML and all required JARs now. It should IMHO be possible to distribute that kar and if you install it you have all the required bundles.

But the feature does not work. Karaf states, that something could not be resolved but the entry is in the feature and the bundle exists in the kar.

**Comment by maggu2810** [comment]
@kaikreuzer 
The javax.activation and javax.xml have an entry in their manifest that are problematic to include that ones in a feature (IMHO).
The problematic line is "Require-Bundle: system.bundle".
I think such a line should not be included in the manifest at all, or I am missing something.

**Comment by maggu2810** [comment]
Okay, have read: http://wiki.osgi.org/wiki/System_Bundle
javax.activation and javax.xml could be installed using "bundle:install" without any problem, but using it in the feature seems (on my system) to be a problem.

<pre>Error executing command: Unable to resolve root: missing requirement [root] osgi.identity; osgi.identity=karaf-oh2-feature; type=karaf.feature; version="[1.0.0.SNAPSHOT,1.0.0.SNAPSHOT]"; filter:="(&(osgi.identity=karaf-oh2-feature)(type=karaf.feature)(version>=1.0.0.SNAPSHOT)(version<=1.0.0.SNAPSHOT))" [caused by: Unable to resolve karaf-oh2-feature/1.0.0.SNAPSHOT: missing requirement [karaf-oh2-feature/1.0.0.SNAPSHOT] osgi.identity; osgi.identity=javax.activation; type=osgi.bundle; version="[1.1.0.v201211130549,1.1.0.v201211130549]"; resolution:=mandatory [caused by: Unable to resolve javax.activation/1.1.0.v201211130549: missing requirement [javax.activation/1.1.0.v201211130549] osgi.wiring.bundle; osgi.wiring.bundle=system.bundle; filter:="(osgi.wiring.bundle=system.bundle)"]]</pre>

If this is not a configuration problem but a Karaf one, we should create a bug entry.

@oliverlietz 
You have written "Jean-Baptiste Onofré works on getting the resource filtering fixed." before. Can you check, if this problem is some misconfiguration by myself or this is a Karaf bug?

**Comment by maggu2810** [comment]
@kaikreuzer 
If you want to give it a try you could test this one.

# Resources

* org.eclipse.osgi.services_3.4.0.v20140312-2051.jar: https://drive.google.com/file/d/0Bx99QXY8p6gvQVRKTUVLazdxUVE/view?usp=sharing
* javax.activation_1.1.0.v201211130549.jar: https://drive.google.com/file/d/0Bx99QXY8p6gvNkwtU2NQa0kzVEk/view?usp=sharing
* javax.xml_1.3.4.v201005080400.jar: https://drive.google.com/file/d/0Bx99QXY8p6gvcDVJbFhDWHFFUmM/view?usp=sharing
* karaf-oh2-tp-feature-1.0-SNAPSHOT.kar: https://drive.google.com/file/d/0Bx99QXY8p6gvLThxRWhRRHMzWnc/view?usp=sharing
* karaf-oh2-feature-1.0-SNAPSHOT.kar: https://drive.google.com/file/d/0Bx99QXY8p6gvVVRocUJ3NFctc1E/view?usp=sharing

# Pre-requirement

* Karaf with Equinox OSGi framework configured and the openHAB 2 system properties / directories.

# Install

1. bundle:install file:'/tmp/oh2/org.eclipse.osgi.services_3.4.0.v20140312-2051.jar'
2. bundle:install file:'/tmp/oh2/javax.activation_1.1.0.v201211130549.jar' 
3. bundle:install file:'/tmp/oh2/javax.xml_1.3.4.v201005080400.jar' 
4. kar:install file:'/tmp/oh2/karaf-oh2-tp-feature-1.0-SNAPSHOT.kar'
5. kar:install file:'/tmp/oh2/karaf-oh2-feature-1.0-SNAPSHOT.kar'

# Install notes

I do not add "org.eclipse.osgi.service" to the targetplatform because this should be perhaps not necessary at all (currently it is necessary to be installed).

The steps 2 and 3 are necessary until Karaf is fixed (or the feature is configured correctly, see http://karaf.922171.n3.nabble.com/4-0-0-M2-feature-install-system-bundle-td4040561.html).

The step 4 installs all non ESH / OH2 bundles that are currently used in the openHAB 2 alpha2 runtime.

The step 5 installs all ESH / OH2 bundles that are currently used in the openHAB 2 alpha2 runtime.

# Comments

* This setup (the target platform) could be bundled to the Karaf deployment and be configured as boot feature, so we could start with the OH2 features first and the non-OH2 dependencies are already present.
* I set "auto-start" to "true" for all bundles in the feature. It seems to be necessary, but we could further inspect this.
* The OSGILogListener of openhab core needs further inspection: 'org.openhab.core.init.internal.OSGILogListener$NLogListener@2f4b83f5' is removed as a LogListener, since it threw an exception.

**Comment by oliverlietz** [comment]
@maggu2810 Why do you need to install `javax.activation_1.1.0.v201211130549.jar`? Karaf comes with `org.apache.servicemix.specs.activation-api-1.1-2.4.0.jar` in lib/endorsed, so `javax.activation`should be present.

**Comment by maggu2810** [comment]
I would like to stop hunting bugs that are triggered by using different bundles then the current openHAB 2 product.
I used Apache Felix and different bundles, that satisfy all dependencies for months, but I stopped my current approaches.
I want to get as close as possible to the current used bundle set first.

**Comment by kaikreuzer** [comment]
Thanks @maggu2810 for driving this forward! 
Is the tool that you mention a temporary solution for you to create the KARs? 
How would this look like in the final solution? We will not have any product definition in this case anymore, so this will have to be built some other way.
Do you actually maintain a branch in your clone where this future build (with a custom Karaf distro as I had started in my branch) is contained?

**Comment by maggu2810** [comment]
Just to save this information: http://karaf.922171.n3.nabble.com/Add-additional-local-maven-repository-how-tp4028299p4040639.html
Perhaps this could be useful for configuration file changes on product creation.

> Is the tool that you mention a temporary solution for you to create the KARs? 
How would this look like in the final solution? We will not have any product definition in this case anymore, so this will have to be built some other way.

So, to keep stuff running in the Eclipse IDE, we need to use p2 instead of Maven dependencies, right?
To refer to dependencies on Karaf we should use Maven.

So, we could maintain the target platform for Karaf for our self by manually editing the files if the target platform that is using p2 repositories changed.

Another approach would be, we are using some custom tools, that handle that for us and we refer just a kar (oh2 targetplatform) that contains all that stuff. "refer" means using this one as a boot feature and it is available on some Maven repo.

I could create a kar that installs all (non-esh+non-oh2 and esh) that is needed for OH2 alpha2, so we could concentrate on the oh2 stuff at the moment.

There is still some stuff that needs to be resolved, too:
* could we stop depend on start levels at all
* https://issues.apache.org/jira/browse/KARAF-2742
* http://karaf.922171.n3.nabble.com/4-0-0-M2-feature-install-system-bundle-td4040561.html

**Comment by maggu2810** [comment]
One thing seems to be solved (http://karaf.922171.n3.nabble.com/4-0-0-M2-feature-install-system-bundle-td4040561.html).
Got the next one: http://karaf.922171.n3.nabble.com/custom-distribution-features-tc4041246.html

**Comment by maggu2810** [comment]
It seems to be known, so let's wait for the fix...
* http://karaf.922171.n3.nabble.com/custom-distribution-features-tp4041246p4041263.html

**Comment by maggu2810** [comment]
It seems to be known, so let's wait for the fix...
* http://karaf.922171.n3.nabble.com/custom-distribution-features-tp4041246p4041263.html
* https://issues.apache.org/jira/browse/KARAF-3805

**Comment by maggu2810** [comment]
So, I started again to move openHAB 2 to a Karaf based distribution.
You could have a look at my development branch at https://github.com/maggu2810/openhab2/tree/master-for-karaf

**Comment by maggu2810** [comment]
I think the migration to the Karaf container is in a working state for a review.
The common stuff is working.
At the moment there is just one thing that NEEDS to be solved. Is there someone that could help?
See the karaf-todo.md file in the branch (it's the starting problem).

**Comment by maggu2810** [comment]
Okay, I know the source of the problem, will report it to ESH.

**Comment by maggu2810** [comment]
Problem solved with eclipse/smarthome#446

**Comment by dvanherbergen** [comment]
3 questions:
1) What is the current status of the work
2) Where is it? https://github.com/maggu2810/openhab2/tree/master-for-karaf gives a 404. 
3) How can I help?

**Comment by kaikreuzer** [comment]
1) Grab it from here and have a look yourself: https://openhab.ci.cloudbees.com/job/openHAB2-Karaf/
2) Right here in this repo: https://github.com/openhab/openhab2/tree/karaf
3) We are tracking issues here: https://github.com/openhab/openhab2/labels/karaf. Not that many entered at the moment, @maggu2810 is doing a lot of further preparation work. @maggu2810, any idea what Davy could best help on right now?

**Comment by maggu2810** [comment]
* a jetty.xml configuration that works with Pax Web and offers the same function as the current ones bundles in the oh2-jetty bundle

**Comment by maggu2810** [comment]
@dvanherbergen contact me and I will give you further instructions, how you could work with my current development branch

**Comment by maggu2810** [comment]
* pull request to get the karaf branch up to date are fine all the time

**Comment by dvanherbergen** [comment]
@kaikreuzer I'll start working on pull requests to get karaf branch inline with the master, so you don't have to spend time on that for now.

**Comment by maggu2810** [comment]
@kaikreuzer Please add the karaf tag
@dvanherbergen as long as #519 is not merged into the upstream karaf branch, you should base your work (the master merges) on "maggu2810:karaf-features" (the branch that should be merged). It will prevent us for a lot of additional conflicts later (IMHO)

**Comment by kaikreuzer** [comment]
@dvanherbergen Great to have you back on board at openHAB :-)
Main effort when merging the master is to define the features (incl. the cfg files) for the new and changed add-ons. Let us know, if there are any questions.

**Comment by dvanherbergen** [comment]
@kaikreuzer glad to be back. I'll give it a go, if I get stuck, you will hear about it..

**Comment by kaikreuzer** [comment]
Note that I have just merged https://github.com/openhab/openhab2/pull/519, so you should be fine to work here on the Karaf branch and don't have to use @maggu2810's fork.

**Comment by dvanherbergen** [comment]
Thanks!

**Comment by maggu2810** [comment]
#521 should merge the current master.
Next step, jetty configuration...

**Comment by dvanherbergen** [comment]
@maggu2810 There is a first version of the jetty config available here https://github.com/dvanherbergen/openhab2/commit/55772bea5ff5254eecfa4320371ff5908ec2c439
Two things are still missing:
* the jetty deployment manager config, not sure if we still need this though
* advanced ssl config like ExcludeCipherSuites. Basic ssl is working.

**Comment by kaikreuzer** [comment]
> the jetty deployment manager config, not sure if we still need this though

Imho we should leave out the whole web application support. The only thing to consider might be an optional folder for serving static content, see https://github.com/openhab/openhab2/issues/311.

**Comment by kaikreuzer** [comment]
Done and available at https://github.com/openhab/openhab-distro
