### ISSUE TITLE
[mqtt] Outgoing Value Format ignored

### ISSUE THREAD

**Issue by rkoshak** [openhab/openhab-addons#6566]
I've not yet had a chance to do an exhaustive set of experiments. This might only be a problem with Percent type Channels or it could be a general problem. See https://community.openhab.org/t/mqtt-how-to-send-integer-value-to-a-dimmer/87327/9 for the discussion.

Further tests indicate that Outgoing Value Format is just completely ignored for any format that is not %s. I've still not tested other Channel types. But when the OVF is the only thing defined on the Channel (i.e. no absloute min/max, no transformation, no custom on/open) it still get's ignored for %d and %.2f type formatting. Only %s appears to be applied (e.g. adding a prefix to the value before publishing).

## Expected Behavior

When defining a Percent Channel you are given the option to set a minimum and maximum value. The percent will be converted to a number between those values (e.g. if the values are set to 0 and 255 a dimmer value of 50 would be converted to 127.5). Many devices cannot handle a floating point value so intuitively one would expect that putting %d in the Outgoing Value Format would convert the 127.5 to 128.

## Current Behavior

The %d put into the Outgoing Value Format appears to be ignored and 127.5 is what get's published given the example above.

## Possible Solution

It is not clear what order the various outgoing transformation fields are evaluated in the Channel config. I would expect the following order:

1.  min/max value, custom on/open off/closed values, and the like
2.  outgoing transformations
3.  outgoing value format

If there is an order and that order differs from above, it should be documented somewhere. Ideally, fixing the order to this would be the most most intuitive.

A work around is to use the following JS transformation:

```
(function(i) {
    if(isNaN(i)) return -1; // choose an appropriate error value
    return Math.round(i)
})(input)
```

## Steps to Reproduce (for Bugs)

1. Create a Generic MQTT Thing and a Percent Channel
2. Set the Absolute Minimum to 0 and Absolute Maximum to 255
3. Add %d to Outgoing Value Format
4. Link the Channel to a Dimmer Item.
5. sendCommand(50) to the Item
6. Verify that 127.5 instead of 127 or 128 is published.

## Context

Many (most?) devices that accept a range of values like this will not accept a floating point value. Intuitively the Outgoing Value Format should round the floating point number to an int. The alternative is to use a JS transformation, but that raises the question of what exactly is the Outgoing Value Format good for then?

## Your Environment

* Version used: openHAB  SNAPSHOT #1770 (I'm waiting to upgrade until the postUpdate problem get's fixed.
* Environment name and version (e.g. Chrome 76, Java 8, Node.js 12.9, ...):official Docker image
* Operating System and version (desktop or mobile, Windows 10, Raspbian Buster, ...): Ubuntu 18.4 base OS.

**Comment by J-N-K** [comment]
Confirmed. This is a bug. The problem is that the command (127.5) already is a string and %d is not a valid format option for strings.

**Comment by davidgraeff** [comment]
Originally formatting happened first and then transformations were applied. Some people didn't like that and the order was changed but the documentation was never updated.

**Comment by rkoshak** [comment]
OK, so the documentation is definitely wrong, but there is another problem here that almost renders the  Absolute Min/Max useless. 

If you are working with a dimmer, it will almost certainly require integer values. It may be 0-100 or 0-255 or some other range but no matter the range, floating point numbers will likely not be supported. As it is currently working, the _only_ way to get an integer out of the Absloute Min/Max is if you also apply a JS transform, in which case what's the point? If I need a JS transform anyway I may as well do the math in the JS transform in the first place.

That's not all. Now, let's say that we need to publish the value as a JSON string and it needs an integer value for the brightness. In that case the _only_ way to do that is through a JS transform too. I can't use `{ something="foo", brightness="%s"}` because the format will print the PercentType as a floating point number: e.g. `{ something="foo", brightness="50.0" }`.

Using a Percent type channel doesn't really buy us anything because almost all the time we will be forced into using a JS transform to get something usable out of it.

**Comment by jochen314** [comment]
@rkoshak : Is this still open?

**Comment by rkoshak** [comment]
As far as I understand, the answer is "you can't because by the time it gets to the formatter it's a String" so I guess this closes the issue. In the original though we weren't using a transformation directly but using the minimum/maximum value fields of the Channel config and I expected the result of that calculation to still be a Number by the time we get to the format field. This doesn't seem to be the case so the expected behavior is impossible.

That's my understanding at least.

**Comment by jochen314** [comment]
No, I ask, because #6755 changed the behaviour and it should be possible now.

**Comment by rkoshak** [comment]
I guess I don't understand the changes than. If the changes make is so the "Expected Behavior" section in the OP now works (i.e. I can use the minimum/maximum value to change the range of values for a dimmer and then %d or %0.f to trim off or round the result of converting the 0-100 value to a 0-255 value (for example) to an integer than yes, this issue is solved.

**Comment by Hilbrand** [comment]
Can this issue be closed?

**Comment by rogierhofboer** [comment]
No. Experience with the current milestone 3.1.0.M3 is this does not work.
Creating a  dimmer value with min and max of 0 and 254.
So the dimmer value from 0-100 is converted to 0...254
Setting %d as format. 
The mqtt message includes decimals and is not an integer:

UID: mqtt:topic:1d261ff3ba:zitkamer_plafond_lamp
label: Zitkamer plafond lamp
thingTypeUID: mqtt:topic
configuration:
  payloadNotAvailable: offline
  availabilityTopic: zigbee2mqtt/bridge/state
  payloadAvailable: online
bridgeUID: mqtt:broker:1d261ff3ba
location: Zitkamer
channels:
  - id: state
    channelTypeUID: mqtt:switch
    label: State
    description: ""
    configuration:
      commandTopic: zigbee2mqtt/zitkamer_plafond_lamp/set/state
      stateTopic: zigbee2mqtt/zitkamer_plafond_lamp/state
      off: OFF
      on: ON
  - id: brightness
    channelTypeUID: mqtt:dimmer
    label: Brightness
    description: ""
    configuration:
      commandTopic: zigbee2mqtt/zitkamer_plafond_lamp/set/brightness
      min: 0
      formatBeforePublish: "%d"
      stateTopic: zigbee2mqtt/zitkamer_plafond_lamp/brightness
      max: 254

Another problem is that an Item created for this channel uses 0-254 as range, while it should use 0-100 as range, I will raise a separate issue for this.

**Comment by hmerk** [comment]
Last action here was 2021, cand thos one be closed now ?

**Comment by rogierhofboer** [comment]
I'm not using openHab at the moment, but if no fix was made, I suspect the issue is still present, unless another overarching change was made, changing this behaviour.

**Comment by rkoshak** [comment]
I've long since forgotten I opened this one. The documentation has been updated. It currently reads:

> formatBeforePublish: Format a value before it is published to the MQTT broker. The default is to just pass the channel/item state. If you want to apply a prefix, say "MYCOLOR,", you would use "MYCOLOR,%s". Currently only "%s" is supported

So this can be closed as the binding is behaving as intended.
