### ISSUE TITLE
[Chromecast] Group Master IP does not change when Chromecast Elect new Master

### ISSUE THREAD

**Issue by chriscolden** [openhab/openhab-addons#7422]
Chromecast audio groups elect a master Chromecast to host the group. This will be the ip of the chromecast but on a different port.

Chromecasts sometimes move the master of the group to another chromecast in the group. When this happens the thing goes offline. The only way to get it back online is to manually change the IP address to the new master, which is a bit trial and error until you find the right ip.

There needs to be a rediscovery process to find where the chromecast group now lives and update the thing.

**Comment by cweitkamp** [comment]
One question: Did you define your audiogroups via textual configuration file?

**Comment by cweitkamp** [comment]
FTR: It looks very similar to #4186 which should have been solved. But I have a theory (see https://community.openhab.org/t/chromecast-audiogroup-has-an-elected-leader-and-it-keeps-changing/73888/9).

**Comment by chriscolden** [comment]
I don't use a thing file and looks like I reported this before. I did some testing for you when the audio groups were not being discovered at all. You fixed that, I'm regularly getting the chromecasts go offline and having to manually update.

**Comment by chriscolden** [comment]
![Screenshot_20200422-184429](https://user-images.githubusercontent.com/20322380/80015314-6e2da700-84c9-11ea-9f1b-31088121c4a0.jpg)
This is my group at the moment. Ive even forced a chromecast discovery to no avail.

**Comment by jimtng** [comment]
I am still experiencing this issue. I am using autodiscovered thing, not textual thing configuration. My audiogroup thing would go offline and it's because the ip changed to another member. The current solution is to manually delete the thing and re-discover.

**Comment by Stefan300381** [comment]
same here. added in OH3 via main UI. after a few days I have to delete and readd

<img width="560" alt="2021-02-21_05h26_23" src="https://user-images.githubusercontent.com/33487900/108615555-a06ba600-7405-11eb-9f2b-7ba23f5c5356.png">

<img width="557" alt="2021-02-21_05h27_30" src="https://user-images.githubusercontent.com/33487900/108615559-a3669680-7405-11eb-8391-327ee363145e.png">

**Comment by Stefan300381** [comment]
just wondering, any chance we will ever see a solution for this? would love to use my audiogroup as my doorbell(s)

**Comment by lsiepel** [comment]
Not specific for groups, but some changes have been applied to discovery related to ip-addresses here: https://github.com/openhab/openhab-addons/pull/14105 
Could you verify if the issue is still active ? There is also a patch to the 3.4 branch, so i guess testing won't be to dificult.

**Comment by lsiepel** [comment]
Have been playing around with the binding and there doesn't seem to be an easy fix. I have not seen any event message related to ip/master change. So the binding is not actively informed from the device itself.

Another possible route would be an event from mDNS. But have not found anything usefull yet when looking at `MDNSDiscoveryParticipant` @lolodomo are you aware of such feature or if there are bindings that can automatically cope with changing ip-addresses?
