### ISSUE TITLE
[mqtt.homeassistant] Implement MQTT Device Trigger component

### ISSUE THREAD

**Issue by bodiroga** [openhab/openhab-addons#7685]
Hi everyone! (and @jochen314 :wink:)

While trying to implement #7656, I have seen that Home Assistant already defines one component to discover event-oriented messages: the [device trigger](https://www.home-assistant.io/integrations/device_trigger.mqtt/). And the best news is that the Zigbee2mqtt project supports it, so we could forget about changing the sensor component and instead focus on implementing this one.

However, there is one thing to consider, because the implementation is not so easy. As stated in its [description page](https://www.home-assistant.io/integrations/device_trigger.mqtt/), the discovery topic only offers one "payload" and "type" per component, so if the remote control offers more than one event type per button (press, double press, long press,...), each event will presented as an individual channel for the openHAB thing. Not cool. To make things more clear, let's take the following example:

Let's suppose we want to integrate the [Ikea Tradfri ON/OFF Switch](https://www.zigbee2mqtt.io/devices/E1743.html) in openHAB through Zigbee2mqtt and the Home Assistant discovery extension. As the device supports 5 different events (on, off, brightness_down, brightness_up and brightness_stop), Zigbee2mqtt will publish 5 different messages to the following topics:

- ```homeassistant/device_automation/0x14b457fffe7eeb7b/click_on/config```
- ```homeassistant/device_automation/0x14b457fffe7eeb7b/click_off/config```
- ```homeassistant/device_automation/0x14b457fffe7eeb7b/click_brightness_down/config```
- ```homeassistant/device_automation/0x14b457fffe7eeb7b/click_brightness_stop/config```
- ```homeassistant/device_automation/0x14b457fffe7eeb7b/click_brightness_up/config```

and each message will have the following structure:

```json
{
    "automation_type":"trigger",
    "type":"click",
    "subtype":"on",
    "payload":"on",
    "topic":"zigbee2mqtt/tradfri-switch-1/click",
    "device": {
        "identifiers": ["zigbee2mqtt_0x14b457fffe7eeb7b"],
        "name":"tradfri-switch-1",
        "sw_version":"Zigbee2mqtt 1.13.0",
        "model":"TRADFRI ON/OFF switch (E1743)",
        "manufacturer":"IKEA"
    }
}
```

As it can be seen, following the openHAB architecture, this should be modeled as a single channel, with the name ```click``` (the ```type``` of the trigger) and firing "on", "off", "brightness_up", "brightness_down" and "brightness_stop" events (the ```subtype```). But, with the current Home Assistant extension architecture, 5 different channels will be created, one for each component. How could we solve this, @jochen314? We could, for example:

- Filter the DeviceTrigger components with the same topic in the [```accept```](https://github.com/openhab/openhab-addons/blob/2.5.x/bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/handler/HomeAssistantThingHandler.java#L258) function of the HomeAssistantThingHandler class, but for that I need to add some public functions to the AbstractComponent class.
- Override the ```equals``` function in the AbstractComponent class to take into account the peculiarities of the DeviceClass component and then, simply apply a stream().distinct() operation in the [```accept```](https://github.com/openhab/openhab-addons/blob/2.5.x/bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/handler/HomeAssistantThingHandler.java#L258) function.

I have started working on the PR, but I'm not sure how to proceed from now on. Any ideas?

Thank you for your help and work. Best regards,

Aitor

**Comment by jochen314** [comment]
Hi,
I am happy to see the device trigger in HA.
But I think, this is not stable yet. I has  been around for just about3 months.
And the definition seems to be different from all the previous components.
For the 'old' style we would have expected a 'topic' and a list of valid payloads, which represent what now is a type.
And I cannot understand, that the action is a 'type' while the object of the action (button1) is a 'sub-type'.

I would say, that we should wait a bit and see, if this is really a stable HA definition.

If the definition says as is, would would need to add the 'sub-type' into the channel id for a trigger.
Ugly :-(

**Comment by bodiroga** [comment]
Hi again @jochen314!

Ok, I will try to implement the component, but in any case the PR will be created as 'Draft', so that we can see how the HA definition evolves :wink: 

Thanks for your help!

**Comment by lolodomo** [comment]
@ccutrer : isn't it covered by #14234 ?

**Comment by ccutrer** [comment]
@lolodomo: Ah yes. I'm surprised I didn't see this issue when I implemented device triggers. I tried to reference existing issues as I was going through the list of component types my devices supported but openHAB didn't. Apparently I missed one :).

Anyhow, yes, the core of this issue of supporting device_automation triggers is now done. As for collapsing multiple triggers to a single channel, that doesn't (fully) work yet. Right now my channels for an Ikea push button are:

 * `mqtt:homeassistant_zigbee2mqtt_5F0x8cf681fffe32e58e:mosquitto:zigbee2mqtt_5F0x8cf681fffe32e58e:0x8cf681fffe32e58e_5Faction_5Fbrightness_5Fmove_5Fup_5Fdevice_5Fautomation#action`
 * `mqtt:homeassistant_zigbee2mqtt_5F0x8cf681fffe32e58e:mosquitto:zigbee2mqtt_5F0x8cf681fffe32e58e:0x8cf681fffe32e58e_5Faction_5Fbrightness_5Fstop_5Fdevice_5Fautomation#action`
 * `mqtt:homeassistant_zigbee2mqtt_5F0x8cf681fffe32e58e:mosquitto:zigbee2mqtt_5F0x8cf681fffe32e58e:0x8cf681fffe32e58e_5Faction_5Fon_5Fdevice_5Fautomation#action`

I've opened https://github.com/openhab/openhab-addons/issues/14295 to address channel IDs in general, and hoping to collapse multiple automation triggers into a single channel while working on that.

**Comment by lolodomo** [comment]
So we can close this issue or you want to keep it open because there is one part not yet covered ?

**Comment by ccutrer** [comment]
I'm in favor of closing this issue unless @bodiroga has objections.

**Comment by lolodomo** [comment]
@bodiroga : do not hesitate to reopen an issue if something is still missing.

**Comment by bodiroga** [comment]
> I'm in favor of closing this issue unless @bodiroga has objections.

My wish would be to have a single channel for all the triggers, or even better, one channel per each subtype (button1, button2, button3, left button...): https://www.home-assistant.io/integrations/device_trigger.mqtt/#subtype

Anyway, right now I have no time for openHAB development, so I'm sure that @ccutrer's job will be awesome 😉 

Thanks for all your work guys!
