### ISSUE TITLE
[MQTT] Dimmer channel on/off properties not sending "ON" or "OFF"

### ISSUE THREAD

**Issue by digitlength** [openhab/openhab-addons#7991]
## Expected Behavior
Background is here: https://community.openhab.org/t/dimmer-values-0-255-into-mqtt-switch-channel-on-off/101191

I have a WLED device which does not explicitly report whether it is _on_ or _off_ - it just reports brightness. However, it _can_ receive _ON_ and _OFF_ strings to turn on and off. I have setup the thing, item and sitemap switch [as shown in this post](https://community.openhab.org/t/dimmer-values-0-255-into-mqtt-switch-channel-on-off/101191/5)

I expected that this setup would send the string "ON" over the _commandTopic_ when the sitemap switch is switched on, and would subsequently receive a number between 0 and 255 on the _stateTopic_ which would be magically transformed into either ON (anything greater than 0) or OFF (for 0).

## Current Behavior
When switching the sitemap switch on, the number 255 (instead of "ON") is sent over the _commandTopic_. When the sitemap switch is off, the number 0 (instead of "OFF" is sent over the _commandTopic_.

Ultimately, I think I don't understand what the on and off options actually do on the dimmer channel. Could you provide some clarification over and above what is documented here: https://www.openhab.org/addons/bindings/mqtt.generic/#channel-type-dimmer

## Steps to Reproduce (for Bugs)
Use the things, items and sitemap definitions provided in the Community post linked above.

## Context
What I would like to do is use a sitemap switch to turn the lights on and off BUT NOT overwrite the currently set brightness value on the WLED device itself.

I actually have this working using a Javascript transform, but thought that the _on_ and _off_ options might enable me to get rid of the transform!

## Your Environment

* Version used: 2.5.5 Release Build
* Environment name and version (e.g. Chrome 76, Java 8, Node.js 12.9, ...): 
* Operating System and version (desktop or mobile, Windows 10, Raspbian Buster, ...): Raspberry Pi 3B+

**Comment by Skinah** [comment]
@digitlength 
There is now a merged WLED binding that you can use which completely bypasses the MQTT system as it uses HTTP to talk to the esp device.

**Comment by digitlength** [comment]
Thanks @Skinah, I'm aware of the WLED binding - great work!

This issue uses WLED as an example implementation, but it's more about the confusing behaviour with the `on` and `off` parameters, as @bodiroga has confirmed.

**Comment by sovapatr** [comment]
I took a stab at this as I was having the same issue trying to use zwavejs2mqtt. [PercentageValue.java](https://github.com/sovapatr/openhab-addons/blob/3e2cec2958ea91882aa4685484ee1b5c816182d1/bundles/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/values/PercentageValue.java)

So far it has been working well for me.

**Comment by brlodi** [comment]
I'm also running into this problem, similarly to @sovapatr, with ZwaveJS2MQTT.

To provide a concrete use-case, per the spec Zwave dimmers expose only a "level" option which is an integer in the range `[0-99]`, with `0` representing 'off'. It can also additionally accept the special value `255`, which is interpreted as "if you are currently off, turn on to your last brightness before you were turned off".

Currently accessing this functionality requires two Channels pointed at the same MQTT topic:

```openhab
Type dimmer : brightness [ min=0, max=99, step=1, stateTopic="foo", commandTopic="bar" ]`
Type switch : power [
    stateTopic="foo",
    transformationPattern="{ transform mapping positive ints to ON}",
    commandTopic="bar"
  ]
```

with associated separate Items. To get it working in a seamless way ends up requiring 2 Channels, 3 Items (one for each channel and one proxy), and a Rule.

Ideally one should be able to do simply

```
Type dimmer : brightness [ min=0, max=99, step=1, on=255, stateTopic="foo", commandTopic="bar" ]`
```

and have one resulting Item in a straightforward way.

In my experience this isn't purely a Zwave-related thing, but is a very common pattern in MQTT-compatible devices.

**Comment by jochen314** [comment]
I am sorry, but I also do not have any background on why the channels behave the way they do.
My best guess it, that the focus during development was on the messages **received** from the device. So the device can sent another string to indicate 'ON'
I would feel happy with separating the handling of messages from and to the device in the code.
So receiving a message would update the state,
Sending a message could update the state and decide, what message is actually transmitted to the device.

The biggest concern I would have with this is compability. We might need to *deprecate* the current types and create new ones with the nwe behavour.

**Comment by Rossko57** [comment]
As a side comment, rollershutter type MQTT channels also "autotransform" commands UP/DOWN to fake position 0 100, whether you want that or not.
Any fix taken for dimmer should be repeated for rollershutter.

In my view, this is a binding limitation.  No matter what scripted transformation a user tries, they cannot distinguish an OFF command from a 0, or ON from 100, because the binding has done its trick first.
It's not hard to see that this is needed sometimes, e.g. a dimmer device where "command turn ON" turns on at last brightness, and "command bright 100" does something different.

I think should be fixed, and the "breaking change" accepted/notified, to bring this binding more in line with standard openHAB behaviors.

**Comment by lsiepel** [comment]
I guess this is still an issue? If so, is the change that is proposed by @sovapatr the right one? If so, could you update your branch to current main and make a PR? If you need any help, let me know and let's try to get this fixed.

**Comment by sovapatr** [comment]
I've moved to home assistant for my zwave devices and no longer have a build environment. I'm pretty sure I was still having issues with zwave dimmers even after my patch, but I can't remember exactly what it was now. Looking back over at my code it was probably that state was still being set to 100% when it received ON. It probably should have just not set state and waited for the device to send it's state after turning on. But that is just a guess as I can't test it currently.

**Comment by lsiepel** [comment]
Ok thanks for coming back to this issue. Is there a use case why one would not use the z-wave binding, but use this ZwaveJS2MQTT ?
This issue still needs to be resolved. But just asking.

**Comment by sovapatr** [comment]
My use case was that I wanted to place my z-wave stick in a more central
location using a raspberry pi than where my openhab server was. Zwavejs
also supported 700 series sticks earlier, allows for much easier firmware
updates, and had better support for the security options. It is also nice
to have nearly all of my smart devices now accessible over mqtt.
