### ISSUE TITLE
[Jeelink] Handler RevoltSensorHandler tried updating the thing status although the handler was already disposed 

### ISSUE THREAD

**Issue by NightDragon1** [openhab/openhab-addons#8509]
## Expected Behavior
When editing the Thing file, Jeelink should stop the Revolt Handlers of the disposed devices. So no warning in the log

## Current Behavior
I have a punch of Revolt devices and a things file for them. Whenever I edit the file while running openhab, and save it to apply the changes, it seems the old devices / Handlers aren't properly stopped and spamming the log. Example:

```
...
2020-09-20 19:56:46.936 [WARN ] [.core.thing.binding.BaseThingHandler] - Handler RevoltSensorHandler tried updating the thing status although the handler was already disposed.
2020-09-20 19:56:46.950 [WARN ] [.core.thing.binding.BaseThingHandler] - Handler RevoltSensorHandler tried updating the thing status although the handler was already disposed.
2020-09-20 19:56:47.254 [WARN ] [.core.thing.binding.BaseThingHandler] - Handler RevoltSensorHandler tried updating the thing status although the handler was already disposed.
...
```
It can only be stopped when restarting openhab.

## Possible Solution
Guess fixing the handler. ;) I'm just a "dump" user...

## Steps to Reproduce (for Bugs)
1. Create a thing file with several Revolt Things
2. Fully startup openhab
3. edit file and save it
--> Issue should appear

## Context
The reason for editing the file: Adding Groups or publish it to alexa, etc...

## Your Environment
*** System Info
SW: Openhabian  [stable]patchday-20200912-805(12917d6) / openHAB 2.5.8 with bundled Jeelink Binding
HW: Raspberry Pi 4

**Comment by NightDragon1** [comment]
Hi @vbier, 

It seems like i just found a issue in the Jeelink/Revolt binding.

BR,
Rob

**Comment by vbier** [comment]
I tried to reproduce this but could not with the steps you have given. It may be because I do not have any revolt sensors. Simply creating a things file and adding/removing/modifying revolt things (with my existing jeelink as bridge) did not give any warnings.

**Comment by lhurt** [comment]
Hi, same problem here.
Actually the behavior takes some time to show. Therefore it could be a bit hard to find it. There's a [community thread here](https://community.openhab.org/t/handler-disposed/49168) that implies that problem could be [a scheduling issue](https://community.openhab.org/t/handler-disposed/49168/7) as the error message for the chromcast binding was pretty similar.

So may be you can have a fresh look at it and find a solution.

An my case the relevant parts of the log look like this

```
-- Restart of OpenHAB --
.... lots of lines skipped
2020-11-07 16:28:41.120 [INFO ] [panel.internal.HABPanelDashboardTile] - Started HABPanel at /habpanel
2020-11-07 16:28:41.236 [INFO ] [openhab.ui.paper.internal.PaperUIApp] - Started Paper UI at /paperui
-- System is up here --
.... lots of lines skipped again
-- This seems interesting --
2020-11-07 17:54:18.670 [WARN ] [core.thing.internal.ThingManagerImpl] - Disposing handler for thing 'jeelink:lgwUsb:f2917bbf' takes more than 5000ms.
2020-11-07 17:54:18.900 [WARN ] [.core.thing.binding.BaseThingHandler] - Handler JeeLinkHandler tried updating the thing status although the handler was already disposed.
2020-11-07 17:54:18.902 [WARN ] [.core.thing.binding.BaseThingHandler] - Handler JeeLinkHandler tried updating the thing status although the handler was already disposed.
2020-11-07 17:54:31.908 [WARN ] [.core.thing.binding.BaseThingHandler] - Handler JeeLinkHandler tried updating the thing status although the handler was already disposed.
2020-11-07 17:54:44.909 [WARN ] [.core.thing.binding.BaseThingHandler] - Handler JeeLinkHandler tried updating the thing status although the handler was already disposed.
-- from now on lines are repeating every 13 seconds
```

Hope this helps to fix the problem as the log flooding is pretty annoying. Please let me know if you require additional information.

Thanks a lot

**Comment by vbier** [comment]
Can you please install https://github.com/vbier/openhab2-addons/raw/jar/bundles/org.openhab.binding.jeelink/org.openhab.binding.jeelink-2.5.9.jar? This might already fix the problem if we are lucky, but also should log a stack trace when trying to update the status once the handler has been disposed. This will then tell us what the problem is.

**Comment by lhurt** [comment]
@vbier Thanks for providing the new bundle. It seems to work so far. The only issue I discovered was that openhab throws this warning.

```
2020-11-10 07:08:00.222 [WARN ] [org.apache.felix.fileinstall        ] - Error while starting bundle: file:/openhab/addons/org.openhab.binding.jeelink-2.5.9.jar
org.osgi.framework.BundleException: Could not resolve module: org.openhab.binding.jeelink [203]
  Unresolved requirement: Import-Package: org.eclipse.smarthome.io.transport.serial

	at org.eclipse.osgi.container.Module.start(Module.java:444) ~[org.eclipse.osgi-3.12.100.jar:?]
	at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:383) ~[org.eclipse.osgi-3.12.100.jar:?]
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.startBundle(DirectoryWatcher.java:1260) [bundleFile:3.6.4]
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.startBundles(DirectoryWatcher.java:1233) [bundleFile:3.6.4]
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.startAllBundles(DirectoryWatcher.java:1221) [bundleFile:3.6.4]
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.doProcess(DirectoryWatcher.java:515) [bundleFile:3.6.4]
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.process(DirectoryWatcher.java:365) [bundleFile:3.6.4]
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.run(DirectoryWatcher.java:316) [bundleFile:3.6.4]
```

The binding works without satisfying this request
```
openhab> feature:list | grep -i serial
openhab-core-config-serial                        x 2.5.0            x          x Uninstalled x distro-2.5.9             x
openhab-core-config-discovery-usbserial           x 2.5.0            x          x Uninstalled x distro-2.5.9             x
openhab-core-io-transport-serial                  x 2.5.0            x          x Uninstalled x distro-2.5.9             x
openhab-core-io-transport-serial-javacomm         x 2.5.0            x          x Uninstalled x distro-2.5.9             x
openhab-core-io-transport-serial-rxtx             x 2.5.0            x          x Uninstalled x distro-2.5.9             x
openhab-core-io-transport-serial-rfc2217          x 2.5.0            x          x Uninstalled x distro-2.5.9             x
openhab-transport-serial                          x 2.5.0            x          x Uninstalled x distro-2.5.9             x Serial Transport
openhab.tp-serial-javacomm                        x 2.5.0            x          x Uninstalled x distro-2.5.9             x
openhab.tp-serial-rxtx                            x 2.5.0            x          x Uninstalled x distro-2.5.9             x
openhab-binding-lgtvserial                        x 2.5.9            x          x Uninstalled x openhab-addons-2.5.9     x LG TV Serial Binding
openhab-binding-serialbutton                      x 2.5.9            x          x Uninstalled x openhab-addons-2.5.9     x Serial Button Binding
openhab-binding-serial1                           x 1.14.0           x          x Uninstalled x openhab-addons-2.5.9     x Serial Binding
```
Strangely enough I experienced an automatic uninstall of that feature when I restarted openhab after a cache clearance.

May be it's possible to get rid of this issue as well.

One more thing. I discovered that I had two Jeelink things configured accessing the same port. Could this have been the root cause of the initial issue?

Will your changes be merged to the OpenHAB code?

Thanks a lot for your effort.

**Comment by vbier** [comment]
Let's wait some time to make sure the problem is fixed. I will then create a pull request to have the changes merged into the official code. This will get rid of the warning.

I don't think this is caused by the two jeelink things.

**Comment by lhurt** [comment]
Agreed. I'll post an update in about one week.

**Comment by lhurt** [comment]
The error specified doesn't show up anymore but there's another very annoying issue.

The Jeelink handler sometimes times out on system start after reboot of the server.
```
2020-11-17 07:17:05.129 [WARN ] [core.thing.internal.ThingManagerImpl] - Initializing handler for thing 'jeelink:jeelinkUsb:a0908614' takes more than 5000ms.
```

After that it is uninstalled. The console shows
```
openhab> feature:list | grep -i jee
openhab-binding-jeelink                           │ 2.5.9            │          │ Uninstalled │ openhab-addons-2.5.9     │ Jeelink Binding
openhab> feature:install openhab-binding-jeelink
openhab> feature:list | grep -i jee
openhab-binding-jeelink                           │ 2.5.9            │ x        │ Started     │ openhab-addons-2.5.9     │ Jeelink Binding
...
openhab> smarthome:things list | grep -i jee
jeelink:jeelinkUsb:a0908614 (Type=Bridge, Status=UNINITIALIZED, Label=JeeLink USB Empfänger, Bridge=null)
jeelink:lacrosse:a0908614:61 (Type=Thing, Status=UNINITIALIZED (BRIDGE_UNINITIALIZED), Label=Balkon Temperatur und Luftfeuchte, Bridge=jeelink:jeelinkUsb:a0908614)
...
openhab> feature:stop openhab-binding-jeelink                                                                                                      
<lots of messages omitted>
openhab> feature:list | grep -i jee
openhab-binding-jeelink                           │ 2.5.9            │ x        │ Resolved    │ openhab-addons-2.5.9     │ Jeelink Binding
openhab> feature:start openhab-binding-jeelink
openhab> feature:list | grep -i jee
openhab-binding-jeelink                           │ 2.5.9            │ x        │ Started     │ openhab-addons-2.5.9     │ Jeelink Binding
openhab> smarthome:things list | grep -i jee
jeelink:jeelinkUsb:a0908614 (Type=Bridge, Status=OFFLINE (CONFIGURATION_ERROR): Port not found: /dev/ttyUSB_JeeLink, Label=JeeLink USB Empfänger, Bridge=null)
jeelink:lacrosse:a0908614:61 (Type=Thing, Status=UNKNOWN, Label=Balkon Temperatur und Luftfeuchte, Bridge=jeelink:jeelinkUsb:a0908614)
```
Even after the reinstall the thing still doesn't go online even after stopping and restarting it. The message about the port is not true. The port is available inside the container and the openhab user has full rights to access it.

After another restart of the docker container and another reinstallation the binding works again as expected.

Any idea what's going on?
Thanks a lot

**Comment by lhurt** [comment]
Another update. The binding somehow uninstalls itself.

openhab.log
```
2020-11-17 09:05:24.070 [WARN ] [shd.server.session.ServerSessionImpl] - exceptionCaught(ServerSessionImpl[openhab@/192.168.1.250:55478])[state=Opened] InterruptedByTimeoutException: null
```
later in events.log
```
2020-11-17 09:34:19.353 [hingStatusInfoChangedEvent] - 'jeelink:jeelinkUsb:a0908614' changed from UNINITIALIZED (HANDLER_MISSING_ERROR) to INITIALIZING
2020-11-17 09:34:19.409 [hingStatusInfoChangedEvent] - 'jeelink:jeelinkUsb:a0908614' changed from INITIALIZING to ONLINE
2020-11-17 09:34:19.415 [hingStatusInfoChangedEvent] - 'jeelink:lacrosse:a0908614:61' changed from UNINITIALIZED (HANDLER_MISSING_ERROR) to INITIALIZING
2020-11-17 09:34:19.427 [hingStatusInfoChangedEvent] - 'jeelink:lacrosse:a0908614:61' changed from INITIALIZING to UNKNOWN
2020-11-17 09:34:31.811 [hingStatusInfoChangedEvent] - 'jeelink:lacrosse:a0908614:61' changed from UNKNOWN to ONLINE
2020-11-17 09:34:31.818 [me.event.ThingUpdatedEvent] - Thing 'jeelink:lacrosse:a0908614:61' has been updated.
2020-11-17 09:34:53.622 [hingStatusInfoChangedEvent] - 'jeelink:lacrosse:a0908614:61' changed from ONLINE to UNINITIALIZED
2020-11-17 09:34:53.627 [hingStatusInfoChangedEvent] - 'jeelink:lacrosse:a0908614:61' changed from UNINITIALIZED to UNINITIALIZED (HANDLER_MISSING_ERROR)
2020-11-17 09:34:53.627 [hingStatusInfoChangedEvent] - 'jeelink:jeelinkUsb:a0908614' changed from ONLINE to UNINITIALIZED
2020-11-17 09:34:53.650 [hingStatusInfoChangedEvent] - 'jeelink:jeelinkUsb:a0908614' changed from UNINITIALIZED to OFFLINE
2020-11-17 09:34:53.653 [hingStatusInfoChangedEvent] - 'jeelink:jeelinkUsb:a0908614' changed from OFFLINE to UNINITIALIZED (HANDLER_MISSING_ERROR)
2020-11-17 09:34:53.739 [thome.event.ExtensionEvent] - Extension 'binding-jeelink' has been uninstalled.
```
very strange. Any idea?

**Comment by vbier** [comment]
Code invoked while starting has not been changed. 

How did you install the jar? Did you deinstall the official binding first (and did you also remove it from addons.cfg if you had it in there)?
If you you did this and have no other bindings installed using serial ports, openHAB will probably remove openhab-transport-serial as the jar does not provide dependencies and openHAB thinks openhab-transport-serial is no longer needed. In this case install it manually before copying the jar to the addons folder, the binding can not run without openhab-transport-serial:
`feature:install openhab-transport-serial`

**Comment by lhurt** [comment]
As I had to go back to the stock binding because your version autounistalled itself, it runs flawless for at lease 3 days. So I'm wondering what happened. I'll wait and provide feedback in one week.
Nevertheless if you @vbier have provided some improvements, everybody would appreciate if you'd contribute it to the project.

**Comment by lsiepel** [comment]
Is this still an issue? I do not see any merged jeelink PR's since opening this issue. But i do know some scheduler related issue have been resolved in core.

**Comment by NightDragon1** [comment]
I haven't seen the issue anymore since a while

**Comment by lsiepel** [comment]
Thank you
