### ISSUE TITLE
[homematic] Dimmer HmIP-BDT not working in Openhab 3

### ISSUE THREAD

**Issue by maedball** [openhab/openhab-addons#8799]
## Expected Behavior
On creation of the HmIP-BDT Dimmer Item via the new UI the Item should have a dimming range of  0-100.

## Current Behavior
Instead it is ranging from 0-1. I also noticed that the Homekit integration is showing the Item as a switch instead of a Dimmer.

![image](https://user-images.githubusercontent.com/23019308/96389603-b85dbf80-11b0-11eb-87a6-aaca3a07e08f.png)

## Steps to Reproduce (for Bugs)
Create a Point (item) in Openhab 3 via the new interface.

## Context
I just started playing with the new Openhab 3.

## Your Environment
Ubuntu 20.04 LTS
Openhab 3 M2
OpenJava 11

**Comment by MHerbst** [comment]
I could reproduce the problem in my environment. 
@ghys Is it intended to have a value between 0 and 1? In OH 2.5 for dimmers values between 0 and 100 are used and it looks like this in Paper UI: 
![image](https://user-images.githubusercontent.com/616792/96495583-61a3c480-1248-11eb-9559-17a5fcf6753a.png)

I can see also some warnings in openhab.log that do not appear in OH 2.5:

``` 
20:16:09.438 [WARN ] [se.internal.SseItemStatesEventBuilder] - Exception while formatting value '69' of item HmIPPDT000DD7098B8F23_Level with format '%.2f %unit%': Conversion = 'u'
```
Because of these warnings, the displayed value is not updated.

If I create a dimmer item in the Model editor it uses values between 0 and 100.

@ghys What do you think? Is this a problem on the UI or a compatibility issue between the binding and the new UI implementation? Maybe some missing information in the channel definition?

**Comment by MHerbst** [comment]
I have checked the Channel Type definition for this channel and this is what the binding returns:
![image](https://user-images.githubusercontent.com/616792/96498762-c7924b00-124c-11eb-8615-b1dc34da40c4.png)

I have compared it with the stateDescription for a Shelly item that is also defined as dimmer:
![image](https://user-images.githubusercontent.com/616792/96499684-0543a380-124e-11eb-9665-f15a18cc2b22.png)

As far as I understand, in Paper UI for a Dimmer the ranges are "translated" to percent values (i.e. ranges between 0 and 100).

**Comment by ghys** [comment]
I think it's weird to have such a state description for a dimmer. The likely problem causing the warning is that it cannot replace `%unit%` in the pattern with the unit, because it's a dimmer and therefore doesn't have a unit, so I suppose in this case it doesn't make the replacement and the string formatter chokes on `%u`... I believe it shouldn't be like that, so at least `%unit%` should be removed from the pattern.
The maximum of 1.01 is also weird since it isn't compatible with the 0.1 step.

> As far as I understand, in Paper UI for a Dimmer the ranges are "translated" to percent values (i.e. ranges between 0 and 100).

We'll have to look for that in the Paper UI code then. In general I'm more of the opinion that clients shouldn't do things like that, and simply respect the state description, but we'll see.
Also apparently the slider suffers from the classic floating point problem...

**Comment by maedball** [comment]
Just 2 stupid questions from my side:

1) the new ui is also called paperui?
2) which module (ui, binding,...) is setting the state description upon creation of an item?
@MHerbst: do you by any chance have the correct values that should be in the state description for the homematic dimmers? I moved straight from config files to the json file so i have no data to compare :-(

**Comment by MHerbst** [comment]
@ghys @maedball The Homematic binding creates all channel definitions dynamically and it retrieves all configuration values directly from Homematic. There are several devices with this weird maximum value of 1.01. For roller shutter controllers I already corrected the values. I will look into the implementation and I think I can correct the maximum value also for dimmers to 1.00.

>  The likely problem causing the warning is that it cannot replace %unit% in the pattern with the unit

I agree, this does not really make sense here. Will try to figure out why it is used for a dimmer. Maybe the idea was to automatically show a `%` character in PaperUI (but this did not work). Interestingly, it does not cause any problems with OH 2.5.9. 

> We'll have to look for that in the Paper UI code then. In general, I'm more of the opinion that clients shouldn't do things like that, and simply respect the state description, but we'll see.

That's what I also expected and that's why I looked into another binding (Shelly) which uses did not use values between 1 and 100 (as expected for a dimmer).

> the new ui is also called paperui?

In the webui git repo "MainUI" is used as the name.

**Comment by maedball** [comment]
Just in case someone wants to know: The Bug is still present in OpenHAB 3 M2. (I updated the description already)

I don't want to put any pressure on this, it is just to let other people know ;-)

**Comment by MHerbst** [comment]
It's on my to do list :-) I had some problems with the development environment, but now I have a working environment and can work on it.

**Comment by MHerbst** [comment]
I think, I have solved the problem. If you like, you can test it with this jar: https://github.com/MHerbst/openhab-addons-test/blob/master/org.openhab.binding.homematic-3.0.0-SNAPSHOT.jar

**Comment by maedball** [comment]
Looks like it is working even without a removal of the items ;-)

Thank you very much!!

**Comment by MHerbst** [comment]
@maedball Can you please re-open the issue? I have not created a PR yet and the solution has not been merged. The issue will automatically be closed during the merge process.

**Comment by XeS0r** [comment]
I currently see this issue with 3.0.0.RC1. But as far as I can see this should have been solved with OH3 M4? Did I miss something on my side?

**Comment by XeS0r** [comment]
I was able to workaround this issue by adding the state information min:0 max:100 to the level item. But I guess this should be the default like you said in one of your earlier posts.

**Comment by MHerbst** [comment]
Did you create the thing with a version prior M4? In this case, it should be sufficient to remove and re-create the thing.

I made a test with a PDT device an RC1 with a fresh installation and it worked without adding state information.

**Comment by XeS0r** [comment]
I also created the thing and the item with RC1. But I upgraded from M5 to RC1 using `sudo apt update/upgrade`. Could that be an Issue? Since that I've restarted openhab multiple times and I've now reproduced this once after an restart too. Do I have to add the CCU again? 

```
/var/lib/openhab/tmp/mvn/org/openhab/addons/bundles/org.openhab.binding.homematic/3.0.0.RC1/org.openhab.binding.homematic-3.0.0.RC1.jar
SHA1: 14ca3d9286d959edbbd60d4c4020b9b877251880
```

**Comment by MHerbst** [comment]
No, it is only related to the thing. What device do you have?  Maybe I will also need some log output, but first of all I need to look into the code.

**Comment by XeS0r** [comment]
HomeMatic Funk-Dimmaktor 1-fach
HM-LC-Dim1T-DR
https://amzn.to/2Kj6sTR

**Comment by MHerbst** [comment]
Ah OK, the fix was only related to HmIP devices. I will have to look into the device documentation.

> Just let me know which information you need.
You can help me by sending me the currently created definition. You will find it in jsondb/org.openhab.core.thing.Thing.json.

Please search (case-insensitive) for a block starting with "homematic:HM-LC-Dim1T-DR" (might be slightly different) and attach the content of the block for this device. It ends at a "}" on column 3.

You could also set the log level for the Homematic binding to TRACE, remove the thing and detect it again. The DEBUG information will also contain relevant information.

**Comment by XeS0r** [comment]
I guess that content is too much therefore I uploaded it to pastebin.
https://pastebin.com/YmBwAMLV

Hope that helps.

**Comment by MHerbst** [comment]
Thanks, this helps. The LEVEL channel is correctly defined as "Dimmer"  Can you please perform two additional test:
The first one is a bit complicated:

1. in Main UI go to Developer Tools/API Explorer
2. expand "channel-types"
3. click on GET /channel-types/{channelTypeUID}
4. click on "Try it out"
5. paste `homematic:HM-LC-Dim1T-DR_1_LEVEL` in text field "channelTypeUID"
6. Press "Execute"
7. Under "Server response" should be a Code of "200" and in "Response body" you will see some JSON output. This output would be interesting for me, especially the block with "stateDescription".

In order to understand why the thing definition is not complete a trace output would help:

1. remove the dimmer thing
2. in the openHAB console set the log level for the Homematic binding to TRACE (`log:set TRACE org.openhab.binding.homematic`).
3. re-discover and re-create the thing again

Post the relevant part from openhab.log (you can attach it here or use pastebin). This should give me the ce

**Comment by XeS0r** [comment]
Here is the response body:
``` json
  "parameters": [
    {
      "defaultValue": "0.0",
      "description": "Delays transmission of a command to the Homematic gateway, duplicate commands are filtered out (in seconds)",
      "label": "Delay",
      "name": "delay",
      "required": false,
      "type": "DECIMAL",
      "min": 0,
      "max": 86400,
      "readOnly": false,
      "multiple": false,
      "advanced": false,
      "verify": false,
      "limitToOptions": true,
      "options": [],
      "filterCriteria": []
    },
    {
      "defaultValue": "0.0",
      "description": "Delays a received event from the Homematic gateway, duplicate events are filtered out (in seconds)",
      "label": "Receive Delay",
      "name": "receiveDelay",
      "required": false,
      "type": "DECIMAL",
      "min": 0,
      "max": 86400,
      "readOnly": false,
      "multiple": false,
      "advanced": false,
      "verify": false,
      "limitToOptions": true,
      "options": [],
      "filterCriteria": []
    }
  ],
  "parameterGroups": [],
  "description": "Dimming value",
  "label": "Level",
  "category": "",
  "itemType": "Dimmer",
  "kind": "STATE",
  "stateDescription": {
    "minimum": 0,
    "maximum": 1,
    "step": 0.1,
    "pattern": "%d %%",
    "readOnly": false,
    "options": []
  },
  "tags": [],
  "UID": "homematic:HM-LC-Dim1T-DR_1_LEVEL",
  "advanced": false
}
```

**Comment by MHerbst** [comment]
OK, I see a possible reason for the problem. The maximum value is 1 and step size 0.1. For the HmIP devices the maximum is set to 100. I think, this can be fixes quite easily and I can probably provide a test jar for testing this afternoon.

**Comment by XeS0r** [comment]
Do you still need the log? I can test the jar for you asap. Just let me know when it's ready.

**Comment by MHerbst** [comment]
No, I don't need it

**Comment by MHerbst** [comment]
You can download a test jar from here: https://github.com/MHerbst/openhab-addons-test . Please remove the existing thing after the installation and recreate it again.

**Comment by XeS0r** [comment]
Maybe I'm doing something wrong. I tried to replace the current jar file and I've tried to copy it to the /usr/share/openhab/addons/ folder. Neither worked. How am I supposed to install this jar file?

**Comment by XeS0r** [comment]
With this package I was not able to reproduce the issue again. Therefore it seems to be solved. Should have read the README in your addons-test repository earlier. Thanks a lot for your work. I appreciate it a lot.

**Comment by MHerbst** [comment]
OK, good to hear, will create a PR for it
