### ISSUE TITLE
[LCN] Reading measurement values with modules before 2013 stops after a while

### ISSUE THREAD

**Issue by harteknut** [openhab/openhab-addons#9740]
## Adding action "send PCK Commands"
In addition to the existing actions
* Hit Key
* Dynamic Text
* Flicker Output
* Relay Timer
 
it would be great if you could add an action send PCK Commands. The purpose is to send free defined PCK Commands, e.g. "MWTA" to pull the variables from old modules. 
Syntax could be:
`val actions = getActions("lcn","lcn:module:b827ebfea4bb:S000M012")`
`actions.sendPCK("MWTA")`

Thanks for your effort,
Simon

## My Environment

* Version used: version: 3.0.0
* buildString: Release Build
* locale: de_DE
* javaVersion: 11.0.9
* javaVendor: Azul Systems, Inc.
* javaVendorVersion: Zulu11.43+88-CA
* osName: Linux
* osVersion: 5.4.79-v7l+
* osArchitecture: arm
* bindings:
  - astro
  - doorbird
  - enocean
  - icloud
  - ipcamera
  - lcn
  - network
  - ntp
  - openweathermap
  - shelly
  - sonos
  - squeezebox
  - zwave

**Comment by fwolter** [comment]
If this is your only use case, the binding supports modules with the old measurement processing. The TVar value is accessible via Variable 1, R1Var and R2Var via Variable 2+3.

**Comment by harteknut** [comment]
Hey Fabian,
thanks for your reply. I thought that the binding should work with my old modules, so i added all the temperaturesensors like this:
`Number:Temperature EG_Flur_Temp_Ist				 "T_av EG Flur [ist: %.1f %unit%]"  		    <temperature>	(gTemperaturen, gEG_Flur_Heizung)			[Measurement, Temperature]    {channel="lcn:module:edb2e504:S000M019:variable#2"}`
I also get a Value for the Item (once, just after start of openhab service), but it will not be actualized during the day. 
Furthermore, I can't see measurement-pings on the LCN-bus (checking with LCN-PRO).

So I thought it would be the easiest way to ping the measurement via periodic rule.

**Comment by harteknut** [comment]
As described in [https://github.com/openhab/openhab-addons/issues/8151#](url), I changed the logging to trace. I can't see any 
`"> M000###.MWTA"` on the log.
After restart of openhab, the MWTAs are send every 30s for a while, then they disapear step-by-step for each module. Heres the last log from module#11:
`2021-01-09 13:19:59.083 [TRACE] [g.lcn.internal.connection.Connection] - Sent: >M000011.MWTA`
`2021-01-09 13:19:59.126 [TRACE] [g.lcn.internal.connection.Connection] - Received: '%M000011.01167`
Is it useful to post the full log here?

**Comment by fwolter** [comment]
Do you have by any chance linked all Channels of the module? There might be a bug that starvation occurs if too many polls fail, as you dont have output 4 or threshold registers 2-4

**Comment by harteknut** [comment]
No, in the example above (module#11) I've only 5 channels linked: 

![channels](https://user-images.githubusercontent.com/16650972/104109207-e80df680-52cb-11eb-971a-6b50c4fdef3f.png)

I attached the openhab log and a lcn-only-filter log of the last openhab start.
[openhab.txt](https://github.com/openhab/openhab-addons/files/5791886/openhab.txt)
[openhab_lcn_only.txt](https://github.com/openhab/openhab-addons/files/5791884/openhab_lcn_only.txt)
The system starts approximately at 12:46 h, the last MWTA-Command is logged at 13:24 h.
Can you see any reasons for this behavior?

**Comment by fwolter** [comment]
I couldn't see whats wrong from your logs, but I fixed some bugs concerning the old measurement processing. Here is the updated JAR https://github.com/fwolter/openhab-addons/releases/download/lcn-v0.1.0/org.openhab.binding.lcn-3.1.0-SNAPSHOT.jar You can drop it into your `addons` folder.

If the error occurs again, you could list the current threads. Maybe there's a locking issue:

- Login to the openHAB console: https://www.openhab.org/docs/administration/console.html
- Enter `threads`

I removed the logs from your post as they contained your password.

**Comment by harteknut** [comment]
It seems you got it!
My openhab is running for 3 hours now, and each module with linked measurement channels is asked for its value every 30 seconds by MWTA respectively MWTB.
I have one issue left, because one single temperature-item is not updated at any time, but I can see its correct value in the trace, so the cause should be located somewhere else in openhab.
Thanks a lot for your effort!

**Comment by fwolter** [comment]
Great that it works now!

**Comment by harteknut** [comment]
Sorry for asking a noob-question again, but I'm still not familiar enough with the karaf console:
After putting the *3.1.0-SNAPSHOT.jar-file in the addons folder, do I have to deactivate the 3.0.0-Binding somehow?
Actual, it seems to me that both versions are acitve:
`openhab> bundle:list -s |grep lcn`
`196 │ Active │  80 │ 3.1.0.202101101503      │ org.openhab.binding.lcn`
`230 │ Active │  80 │ 3.0.0                   │ org.openhab.binding.lcn`

or not?
`openhab> feature:list |grep lcn`
`openhab-binding-lcn                               │ 3.0.0            │ x        │ Started     │ openhab-addons-3.0.0     │ Lcn Binding`

**Comment by fwolter** [comment]
AFAIK the new version should be used automatically. To be sure you can uninstall the LCN binding in the UI.

**Comment by harteknut** [comment]
I'm forced to reopen the issue again, it seems that I was to hasty. After sereval hours, the MWTAs disapear again step-by-step.
Now I did everything new from scratch:
Fresh OH3 installation, no 3.0.0-binding via UI, only the new 3.1.0-jar-file. Restart of LCN-PKE, restart of oh with clean-cache.
Nothing helps.
I made the list of threads as you mentioned before: 
[threads.txt](https://github.com/openhab/openhab-addons/files/5805010/threads.txt)

**Comment by fwolter** [comment]
I made the measurement processing a bit more resilient when it comes to lost frames. Also the firmware is now read from the Thing properties. This has been requested from the module at runtime before. If this failed, the measurement values couldn't be read. I also added more debug logging output. Have a try: https://github.com/fwolter/openhab-addons/releases/download/lcn2021-01-13b/org.openhab.binding.lcn-3.1.0-SNAPSHOT.jar

**Comment by harteknut** [comment]
Thanks again! The binding talks a LOT now :-)
But again, after one day, the MWTAs disapear. It seems that the Binding runs over the sceduled Timestamp and waits vor the next event:
`2021-01-15 11:46:35.804 [INFO ] [cn.internal.connection.RequestStatus] - S000M010 VARIABLE 2: nextRequestTimeStamp: 112608650825511 timeoutMSec: 3500 currTime: 131577676308594`
As soon as I have acess to my laptop (homeschooling comes first...), I will upload the log of the crucial moment.

**Comment by harteknut** [comment]
Sorry, I was too late. The moments of the crucial events are no longer in the log, because there are only 8 logfiles and with lcn-logging set to TRACE, each file contains only half of an hour. I attached a few minutes 
[openhab.txt](https://github.com/openhab/openhab-addons/files/5820502/openhab.txt)
file instead. Is this enogh information for analysis?

**Comment by fwolter** [comment]
As you already noticed the time of the next request is in the past. This can happen if `System.nanoTime()` overflows, which should only happen every 292 years, according java spec. What hardware/software platform are you using?

The binding uses `System.currentTimeMillis()` now, which surely won't overflow in the next time. Try the new JAR:
https://github.com/fwolter/openhab-addons/releases/download/lcn2021-01-15/org.openhab.binding.lcn-3.1.0-SNAPSHOT.jar

**Comment by harteknut** [comment]
Thanks, for the fast reply, I just startet the new file.

I'm running OH 3.0.0 (openHABian) on a  Raspberry Pi 4:
```
###############################################################################
###############  openHABianDevice  ############################################
###############################################################################
##        Ip = x.x.x.x
##   Release = Raspbian GNU/Linux 10 (buster)
##    Kernel = Linux 5.4.79-v7l+
##  Platform = Raspberry Pi 4 Model B Rev 1.1
##    Uptime = 1 day(s). 17:43:13
## CPU Usage = 4.51% avg over 4 cpu(s) (4 core(s) x 1 socket(s))
##  CPU Load = 1m: 0.91, 5m: 0.50, 15m: 0.35
##    Memory = Free: 2.45GB (65%), Used: 1.33GB (35%), Total: 3.78GB
##      Swap = Free: 1.99GB (100%), Used: 0.00GB (0%), Total: 1.99GB
##      Root = Free: 22.99GB (82%), Used: 4.76GB (18%), Total: 28.98GB
##   Updates = 14 apt updates available.
##  Sessions = 1 session(s)
## Processes = 123 running processes of 32768 maximum processes
###############################################################################

                          _   _     _     ____   _               
  ___   ___   ___   ___  | | | |   / \   | __ ) (_)  ____   ___  
 / _ \ / _ \ / _ \ / _ \ | |_| |  / _ \  |  _ \ | | / _  \ / _ \ 
| (_) | (_) |  __/| | | ||  _  | / ___ \ | |_) )| || (_) || | | |
 \___/|  __/ \___/|_| |_||_| |_|/_/   \_\|____/ |_| \__|_||_| | |
      |_|                          3.0.0 - Release Build          
```
![Version](https://user-images.githubusercontent.com/16650972/104750058-da38f500-5753-11eb-9fea-ec412e975737.png)

**Comment by fwolter** [comment]
I forgot to replace one timer. The processing might be broken. But I think above assumption is not the problem. I'm trying to reproduce it further.

**Comment by fwolter** [comment]
Can you test if the module executes any other command issued by OH if the error occurs? E.g. switching an output or relay.

**Comment by harteknut** [comment]
The last version from 16:38h does not process the values at all.
The other commands (switching outputs, relays or changing reguator setpoints) work well, even after the binding has cancelled its measurement support for the module.

**Comment by fwolter** [comment]
Yeah, the last version was broken. Just to be sure, the version before the previous executed other commands if the measurement processing has stopped?

**Comment by harteknut** [comment]
Let me doublecheck this fact again. I put the file from the post 13.01. 18:49h back on the folder and will test it when the measurement processing will stop.

**Comment by harteknut** [comment]
I checked again this morning:
After the measurement process has stopped, the affected modules still execute other commands like switching outputs or changing rvarsetpoint.

**Comment by fwolter** [comment]
I could track the error down further. The timers are still running, but the frame is not sent for some reason. I adjusted the log messages accordingly and I fixed an issue. Please watch out for the log message "Failed to generate PCK message". Here is the new JAR: https://github.com/fwolter/openhab-addons/releases/download/lcn2021-01-16/org.openhab.binding.lcn-3.1.0-SNAPSHOT.jar

**Comment by harteknut** [comment]
Thanks, `202101161036` ist running...

**Comment by harteknut** [comment]
Here is the moment when M042 quits measurement processing. The last MWTA is logged at 13:50:01. Since now, I have no "Failed to generate PCK message"-logs. Here is the crucial moment in the openhab-log:
[openhab_log_M042.txt](https://github.com/openhab/openhab-addons/files/5824431/openhab_log_M042.txt)

**Comment by fwolter** [comment]
When the error occurs, your log shows that R1Var is unlocked, then the R1Var setpoint is requested, but before the module answers with the setpoint, the unlock acknowledge comes in with a special R1Var setpoint message and finally the answer to the R1Var setpoint request is lost. We seem to have different firmwares which behave slightly different or it was a coincidence that the setpoint frame was lost. That's why I can't reproduce the error. In any case, I changed something which could cause this issue. Have a try: https://github.com/fwolter/openhab-addons/releases/download/lcn2021-16-01-b/org.openhab.binding.lcn-3.1.0-SNAPSHOT.jar

**Comment by harteknut** [comment]
Thanks, 202101161633 ist running...

**Comment by harteknut** [comment]
Here is a short interim summary after one day:
- All modules are still asked for their values every 30 seconds by MWTA !
- I see a lot of `S000M###: Resetting: VARIABLE2` and `S000M###: Processing VARIABLE2 false UNKNOWN` in the log.
Should  I be worried about that?
- All the rest seems to work fine!

Heres the log of the last hours:
[openhab.txt](https://github.com/openhab/openhab-addons/files/5826791/openhab.txt)

**Comment by fwolter** [comment]
Great that it works! The both messages are just right.

**Comment by fwolter** [comment]
I made a release candidate JAR with the only change to adjust the logging to a normal level again. Would be glad if you can test it before it is being released. https://github.com/fwolter/openhab-addons/releases/download/lcn2021-19-01/org.openhab.binding.lcn-3.1.0-SNAPSHOT.jar

**Comment by harteknut** [comment]
Hey Fabian,
thanks a lot for your effort, top job! I'm very glad that it works!
202101191712 is running, I'll keep you up to date.

**Comment by harteknut** [comment]
Nothing unusual happens the last 24h, so I think we can close this issue.
I'm very glad with my LCN-and-openHAB-System and OH3 works like a charm!
